#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 131
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 80
#define ALIAS_COUNT 0
#define TOKEN_COUNT 35
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_SEMI = 1,
  anon_sym_MATCH = 2,
  anon_sym_LPAREN = 3,
  anon_sym_RPAREN = 4,
  anon_sym_LT_DASH = 5,
  anon_sym_DASH_GT = 6,
  anon_sym_DASH = 7,
  anon_sym_LBRACK = 8,
  anon_sym_RBRACK = 9,
  anon_sym_COLON = 10,
  anon_sym_PIPE = 11,
  anon_sym_LBRACE = 12,
  anon_sym_COMMA = 13,
  anon_sym_RBRACE = 14,
  anon_sym_WHERE = 15,
  anon_sym_CREATE = 16,
  anon_sym_RETURN = 17,
  anon_sym_IN = 18,
  anon_sym_AND = 19,
  aux_sym_expression_token1 = 20,
  aux_sym_expression_token2 = 21,
  anon_sym_NOT = 22,
  anon_sym_XOR = 23,
  anon_sym_OR = 24,
  anon_sym_EQ_TILDE = 25,
  anon_sym_EQ = 26,
  anon_sym_DOT = 27,
  anon_sym_DOLLAR = 28,
  sym_decimal_integer_literal = 29,
  anon_sym_SQUOTE = 30,
  aux_sym_string_literal_token1 = 31,
  anon_sym_DQUOTE = 32,
  aux_sym_string_literal_token2 = 33,
  sym_identifier = 34,
  sym_cypher = 35,
  sym__query = 36,
  sym__reading_clause = 37,
  sym_match = 38,
  sym__pattern = 39,
  sym_pattern_element = 40,
  sym__pattern_element_chain = 41,
  sym__relationship_pattern = 42,
  sym_relationship_detail = 43,
  sym_relationship_types = 44,
  sym_rel_type_name = 45,
  sym_node_pattern = 46,
  sym_node_labels = 47,
  sym_node_label = 48,
  sym_label_name = 49,
  sym_properties = 50,
  sym_map_literal = 51,
  sym_where = 52,
  sym__updating_clause = 53,
  sym_create = 54,
  sym_return = 55,
  sym__projection_items = 56,
  sym__projection_item = 57,
  sym_expression = 58,
  sym_list = 59,
  sym_property_lookup = 60,
  sym_property_key_name = 61,
  sym__schema_name = 62,
  sym__atom = 63,
  sym_parameter = 64,
  sym_function_invocation = 65,
  sym_function_name = 66,
  sym__literal = 67,
  sym_string_literal = 68,
  sym_variable = 69,
  sym__symbolic_name = 70,
  aux_sym__query_repeat1 = 71,
  aux_sym__query_repeat2 = 72,
  aux_sym_pattern_element_repeat1 = 73,
  aux_sym_relationship_types_repeat1 = 74,
  aux_sym_node_labels_repeat1 = 75,
  aux_sym_map_literal_repeat1 = 76,
  aux_sym__projection_items_repeat1 = 77,
  aux_sym_expression_repeat1 = 78,
  aux_sym_list_repeat1 = 79,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SEMI] = ";",
  [anon_sym_MATCH] = "MATCH",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LT_DASH] = "<-",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_DASH] = "-",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_COLON] = ":",
  [anon_sym_PIPE] = "|",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACE] = "}",
  [anon_sym_WHERE] = "WHERE",
  [anon_sym_CREATE] = "CREATE",
  [anon_sym_RETURN] = "RETURN",
  [anon_sym_IN] = "IN",
  [anon_sym_AND] = "AND",
  [aux_sym_expression_token1] = "expression_token1",
  [aux_sym_expression_token2] = "expression_token2",
  [anon_sym_NOT] = "NOT",
  [anon_sym_XOR] = "XOR",
  [anon_sym_OR] = "OR",
  [anon_sym_EQ_TILDE] = "=~",
  [anon_sym_EQ] = "=",
  [anon_sym_DOT] = ".",
  [anon_sym_DOLLAR] = "$",
  [sym_decimal_integer_literal] = "decimal_integer_literal",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_string_literal_token1] = "string_literal_token1",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_literal_token2] = "string_literal_token2",
  [sym_identifier] = "identifier",
  [sym_cypher] = "cypher",
  [sym__query] = "_query",
  [sym__reading_clause] = "_reading_clause",
  [sym_match] = "match",
  [sym__pattern] = "_pattern",
  [sym_pattern_element] = "pattern_element",
  [sym__pattern_element_chain] = "_pattern_element_chain",
  [sym__relationship_pattern] = "_relationship_pattern",
  [sym_relationship_detail] = "relationship_detail",
  [sym_relationship_types] = "relationship_types",
  [sym_rel_type_name] = "rel_type_name",
  [sym_node_pattern] = "node_pattern",
  [sym_node_labels] = "node_labels",
  [sym_node_label] = "node_label",
  [sym_label_name] = "label_name",
  [sym_properties] = "properties",
  [sym_map_literal] = "map_literal",
  [sym_where] = "where",
  [sym__updating_clause] = "_updating_clause",
  [sym_create] = "create",
  [sym_return] = "return",
  [sym__projection_items] = "_projection_items",
  [sym__projection_item] = "_projection_item",
  [sym_expression] = "expression",
  [sym_list] = "list",
  [sym_property_lookup] = "property_lookup",
  [sym_property_key_name] = "property_key_name",
  [sym__schema_name] = "_schema_name",
  [sym__atom] = "_atom",
  [sym_parameter] = "parameter",
  [sym_function_invocation] = "function_invocation",
  [sym_function_name] = "function_name",
  [sym__literal] = "_literal",
  [sym_string_literal] = "string_literal",
  [sym_variable] = "variable",
  [sym__symbolic_name] = "_symbolic_name",
  [aux_sym__query_repeat1] = "_query_repeat1",
  [aux_sym__query_repeat2] = "_query_repeat2",
  [aux_sym_pattern_element_repeat1] = "pattern_element_repeat1",
  [aux_sym_relationship_types_repeat1] = "relationship_types_repeat1",
  [aux_sym_node_labels_repeat1] = "node_labels_repeat1",
  [aux_sym_map_literal_repeat1] = "map_literal_repeat1",
  [aux_sym__projection_items_repeat1] = "_projection_items_repeat1",
  [aux_sym_expression_repeat1] = "expression_repeat1",
  [aux_sym_list_repeat1] = "list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_MATCH] = anon_sym_MATCH,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LT_DASH] = anon_sym_LT_DASH,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_WHERE] = anon_sym_WHERE,
  [anon_sym_CREATE] = anon_sym_CREATE,
  [anon_sym_RETURN] = anon_sym_RETURN,
  [anon_sym_IN] = anon_sym_IN,
  [anon_sym_AND] = anon_sym_AND,
  [aux_sym_expression_token1] = aux_sym_expression_token1,
  [aux_sym_expression_token2] = aux_sym_expression_token2,
  [anon_sym_NOT] = anon_sym_NOT,
  [anon_sym_XOR] = anon_sym_XOR,
  [anon_sym_OR] = anon_sym_OR,
  [anon_sym_EQ_TILDE] = anon_sym_EQ_TILDE,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [sym_decimal_integer_literal] = sym_decimal_integer_literal,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_string_literal_token1] = aux_sym_string_literal_token1,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_literal_token2] = aux_sym_string_literal_token2,
  [sym_identifier] = sym_identifier,
  [sym_cypher] = sym_cypher,
  [sym__query] = sym__query,
  [sym__reading_clause] = sym__reading_clause,
  [sym_match] = sym_match,
  [sym__pattern] = sym__pattern,
  [sym_pattern_element] = sym_pattern_element,
  [sym__pattern_element_chain] = sym__pattern_element_chain,
  [sym__relationship_pattern] = sym__relationship_pattern,
  [sym_relationship_detail] = sym_relationship_detail,
  [sym_relationship_types] = sym_relationship_types,
  [sym_rel_type_name] = sym_rel_type_name,
  [sym_node_pattern] = sym_node_pattern,
  [sym_node_labels] = sym_node_labels,
  [sym_node_label] = sym_node_label,
  [sym_label_name] = sym_label_name,
  [sym_properties] = sym_properties,
  [sym_map_literal] = sym_map_literal,
  [sym_where] = sym_where,
  [sym__updating_clause] = sym__updating_clause,
  [sym_create] = sym_create,
  [sym_return] = sym_return,
  [sym__projection_items] = sym__projection_items,
  [sym__projection_item] = sym__projection_item,
  [sym_expression] = sym_expression,
  [sym_list] = sym_list,
  [sym_property_lookup] = sym_property_lookup,
  [sym_property_key_name] = sym_property_key_name,
  [sym__schema_name] = sym__schema_name,
  [sym__atom] = sym__atom,
  [sym_parameter] = sym_parameter,
  [sym_function_invocation] = sym_function_invocation,
  [sym_function_name] = sym_function_name,
  [sym__literal] = sym__literal,
  [sym_string_literal] = sym_string_literal,
  [sym_variable] = sym_variable,
  [sym__symbolic_name] = sym__symbolic_name,
  [aux_sym__query_repeat1] = aux_sym__query_repeat1,
  [aux_sym__query_repeat2] = aux_sym__query_repeat2,
  [aux_sym_pattern_element_repeat1] = aux_sym_pattern_element_repeat1,
  [aux_sym_relationship_types_repeat1] = aux_sym_relationship_types_repeat1,
  [aux_sym_node_labels_repeat1] = aux_sym_node_labels_repeat1,
  [aux_sym_map_literal_repeat1] = aux_sym_map_literal_repeat1,
  [aux_sym__projection_items_repeat1] = aux_sym__projection_items_repeat1,
  [aux_sym_expression_repeat1] = aux_sym_expression_repeat1,
  [aux_sym_list_repeat1] = aux_sym_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_MATCH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_WHERE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CREATE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RETURN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_IN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_expression_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_expression_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_NOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_XOR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_OR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [sym_decimal_integer_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_literal_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_cypher] = {
    .visible = true,
    .named = true,
  },
  [sym__query] = {
    .visible = false,
    .named = true,
  },
  [sym__reading_clause] = {
    .visible = false,
    .named = true,
  },
  [sym_match] = {
    .visible = true,
    .named = true,
  },
  [sym__pattern] = {
    .visible = false,
    .named = true,
  },
  [sym_pattern_element] = {
    .visible = true,
    .named = true,
  },
  [sym__pattern_element_chain] = {
    .visible = false,
    .named = true,
  },
  [sym__relationship_pattern] = {
    .visible = false,
    .named = true,
  },
  [sym_relationship_detail] = {
    .visible = true,
    .named = true,
  },
  [sym_relationship_types] = {
    .visible = true,
    .named = true,
  },
  [sym_rel_type_name] = {
    .visible = true,
    .named = true,
  },
  [sym_node_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_node_labels] = {
    .visible = true,
    .named = true,
  },
  [sym_node_label] = {
    .visible = true,
    .named = true,
  },
  [sym_label_name] = {
    .visible = true,
    .named = true,
  },
  [sym_properties] = {
    .visible = true,
    .named = true,
  },
  [sym_map_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_where] = {
    .visible = true,
    .named = true,
  },
  [sym__updating_clause] = {
    .visible = false,
    .named = true,
  },
  [sym_create] = {
    .visible = true,
    .named = true,
  },
  [sym_return] = {
    .visible = true,
    .named = true,
  },
  [sym__projection_items] = {
    .visible = false,
    .named = true,
  },
  [sym__projection_item] = {
    .visible = false,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_property_lookup] = {
    .visible = true,
    .named = true,
  },
  [sym_property_key_name] = {
    .visible = true,
    .named = true,
  },
  [sym__schema_name] = {
    .visible = false,
    .named = true,
  },
  [sym__atom] = {
    .visible = false,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_function_invocation] = {
    .visible = true,
    .named = true,
  },
  [sym_function_name] = {
    .visible = true,
    .named = true,
  },
  [sym__literal] = {
    .visible = false,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym__symbolic_name] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__query_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__query_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pattern_element_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_relationship_types_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_node_labels_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_map_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__projection_items_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(32);
      if (lookahead == '"') ADVANCE(68);
      if (lookahead == '$') ADVANCE(62);
      if (lookahead == '\'') ADVANCE(65);
      if (lookahead == '(') ADVANCE(35);
      if (lookahead == ')') ADVANCE(36);
      if (lookahead == '+') ADVANCE(53);
      if (lookahead == ',') ADVANCE(46);
      if (lookahead == '-') ADVANCE(40);
      if (lookahead == '.') ADVANCE(61);
      if (lookahead == '0') ADVANCE(63);
      if (lookahead == ':') ADVANCE(43);
      if (lookahead == ';') ADVANCE(33);
      if (lookahead == '<') ADVANCE(3);
      if (lookahead == '=') ADVANCE(60);
      if (lookahead == 'A') ADVANCE(15);
      if (lookahead == 'C') ADVANCE(22);
      if (lookahead == 'I') ADVANCE(16);
      if (lookahead == 'M') ADVANCE(4);
      if (lookahead == 'N') ADVANCE(18);
      if (lookahead == 'O') ADVANCE(20);
      if (lookahead == 'R') ADVANCE(10);
      if (lookahead == 'W') ADVANCE(14);
      if (lookahead == 'X') ADVANCE(19);
      if (lookahead == '[') ADVANCE(41);
      if (lookahead == ']') ADVANCE(42);
      if (lookahead == '{') ADVANCE(45);
      if (lookahead == '|') ADVANCE(44);
      if (lookahead == '}') ADVANCE(47);
      if (lookahead == '%' ||
          ('*' <= lookahead && lookahead <= '/')) ADVANCE(54);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(64);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(68);
      if (lookahead == '$') ADVANCE(62);
      if (lookahead == '\'') ADVANCE(65);
      if (lookahead == '-') ADVANCE(40);
      if (lookahead == '0') ADVANCE(63);
      if (lookahead == 'N') ADVANCE(71);
      if (lookahead == '[') ADVANCE(41);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(64);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 2:
      if (lookahead == '(') ADVANCE(35);
      if (lookahead == ')') ADVANCE(36);
      if (lookahead == ':') ADVANCE(43);
      if (lookahead == ']') ADVANCE(42);
      if (lookahead == '{') ADVANCE(45);
      if (lookahead == '}') ADVANCE(47);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 3:
      if (lookahead == '-') ADVANCE(37);
      END_STATE();
    case 4:
      if (lookahead == 'A') ADVANCE(25);
      END_STATE();
    case 5:
      if (lookahead == 'A') ADVANCE(28);
      END_STATE();
    case 6:
      if (lookahead == 'C') ADVANCE(13);
      END_STATE();
    case 7:
      if (lookahead == 'D') ADVANCE(52);
      END_STATE();
    case 8:
      if (lookahead == 'E') ADVANCE(48);
      END_STATE();
    case 9:
      if (lookahead == 'E') ADVANCE(49);
      END_STATE();
    case 10:
      if (lookahead == 'E') ADVANCE(27);
      END_STATE();
    case 11:
      if (lookahead == 'E') ADVANCE(24);
      END_STATE();
    case 12:
      if (lookahead == 'E') ADVANCE(5);
      END_STATE();
    case 13:
      if (lookahead == 'H') ADVANCE(34);
      END_STATE();
    case 14:
      if (lookahead == 'H') ADVANCE(11);
      END_STATE();
    case 15:
      if (lookahead == 'N') ADVANCE(7);
      END_STATE();
    case 16:
      if (lookahead == 'N') ADVANCE(51);
      END_STATE();
    case 17:
      if (lookahead == 'N') ADVANCE(50);
      END_STATE();
    case 18:
      if (lookahead == 'O') ADVANCE(26);
      END_STATE();
    case 19:
      if (lookahead == 'O') ADVANCE(21);
      END_STATE();
    case 20:
      if (lookahead == 'R') ADVANCE(58);
      END_STATE();
    case 21:
      if (lookahead == 'R') ADVANCE(57);
      END_STATE();
    case 22:
      if (lookahead == 'R') ADVANCE(12);
      END_STATE();
    case 23:
      if (lookahead == 'R') ADVANCE(17);
      END_STATE();
    case 24:
      if (lookahead == 'R') ADVANCE(8);
      END_STATE();
    case 25:
      if (lookahead == 'T') ADVANCE(6);
      END_STATE();
    case 26:
      if (lookahead == 'T') ADVANCE(55);
      END_STATE();
    case 27:
      if (lookahead == 'T') ADVANCE(29);
      END_STATE();
    case 28:
      if (lookahead == 'T') ADVANCE(9);
      END_STATE();
    case 29:
      if (lookahead == 'U') ADVANCE(23);
      END_STATE();
    case 30:
      if (eof) ADVANCE(32);
      if (lookahead == '(') ADVANCE(35);
      if (lookahead == ')') ADVANCE(36);
      if (lookahead == ',') ADVANCE(46);
      if (lookahead == '.') ADVANCE(61);
      if (lookahead == ':') ADVANCE(43);
      if (lookahead == ';') ADVANCE(33);
      if (lookahead == '=') ADVANCE(60);
      if (lookahead == 'A') ADVANCE(15);
      if (lookahead == 'C') ADVANCE(22);
      if (lookahead == 'I') ADVANCE(16);
      if (lookahead == 'M') ADVANCE(4);
      if (lookahead == 'O') ADVANCE(20);
      if (lookahead == 'R') ADVANCE(10);
      if (lookahead == 'X') ADVANCE(19);
      if (lookahead == ']') ADVANCE(42);
      if (lookahead == '}') ADVANCE(47);
      if (('+' <= lookahead && lookahead <= '-')) ADVANCE(53);
      if (lookahead == '%' ||
          ('*' <= lookahead && lookahead <= '/')) ADVANCE(54);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(30)
      END_STATE();
    case 31:
      if (eof) ADVANCE(32);
      if (lookahead == ')') ADVANCE(36);
      if (lookahead == '-') ADVANCE(39);
      if (lookahead == ';') ADVANCE(33);
      if (lookahead == '<') ADVANCE(3);
      if (lookahead == 'C') ADVANCE(22);
      if (lookahead == 'M') ADVANCE(4);
      if (lookahead == 'R') ADVANCE(10);
      if (lookahead == 'W') ADVANCE(14);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(31)
      END_STATE();
    case 32:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_MATCH);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_LT_DASH);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '>') ADVANCE(38);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_WHERE);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_CREATE);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_RETURN);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_IN);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_AND);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_expression_token1);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym_expression_token2);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_NOT);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_NOT);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_XOR);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_OR);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_EQ_TILDE);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '~') ADVANCE(59);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_decimal_integer_literal);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_decimal_integer_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(64);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(66);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(67);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(aux_sym_string_literal_token2);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(69);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(70);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym_string_literal_token2);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(70);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'O') ADVANCE(72);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'T') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 30},
  [3] = {.lex_state = 30},
  [4] = {.lex_state = 30},
  [5] = {.lex_state = 30},
  [6] = {.lex_state = 30},
  [7] = {.lex_state = 30},
  [8] = {.lex_state = 30},
  [9] = {.lex_state = 30},
  [10] = {.lex_state = 30},
  [11] = {.lex_state = 30},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 30},
  [14] = {.lex_state = 30},
  [15] = {.lex_state = 30},
  [16] = {.lex_state = 30},
  [17] = {.lex_state = 30},
  [18] = {.lex_state = 30},
  [19] = {.lex_state = 30},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 30},
  [22] = {.lex_state = 30},
  [23] = {.lex_state = 30},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 31},
  [38] = {.lex_state = 31},
  [39] = {.lex_state = 31},
  [40] = {.lex_state = 30},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 30},
  [44] = {.lex_state = 30},
  [45] = {.lex_state = 30},
  [46] = {.lex_state = 30},
  [47] = {.lex_state = 30},
  [48] = {.lex_state = 31},
  [49] = {.lex_state = 31},
  [50] = {.lex_state = 31},
  [51] = {.lex_state = 30},
  [52] = {.lex_state = 31},
  [53] = {.lex_state = 31},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 2},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 2},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 2},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 1},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 2},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 2},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 2},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 2},
  [81] = {.lex_state = 2},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 2},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 1},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 1},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 1},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 1},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 69},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 66},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_MATCH] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LT_DASH] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_WHERE] = ACTIONS(1),
    [anon_sym_CREATE] = ACTIONS(1),
    [anon_sym_RETURN] = ACTIONS(1),
    [anon_sym_IN] = ACTIONS(1),
    [anon_sym_AND] = ACTIONS(1),
    [aux_sym_expression_token1] = ACTIONS(1),
    [aux_sym_expression_token2] = ACTIONS(1),
    [anon_sym_NOT] = ACTIONS(1),
    [anon_sym_XOR] = ACTIONS(1),
    [anon_sym_OR] = ACTIONS(1),
    [anon_sym_EQ_TILDE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [sym_decimal_integer_literal] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
  },
  [1] = {
    [sym_cypher] = STATE(128),
    [sym__query] = STATE(102),
    [sym__reading_clause] = STATE(41),
    [sym_match] = STATE(41),
    [sym__updating_clause] = STATE(55),
    [sym_create] = STATE(55),
    [sym_return] = STATE(102),
    [aux_sym__query_repeat1] = STATE(41),
    [aux_sym__query_repeat2] = STATE(55),
    [anon_sym_MATCH] = ACTIONS(3),
    [anon_sym_CREATE] = ACTIONS(5),
    [anon_sym_RETURN] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(11), 1,
      anon_sym_IN,
    ACTIONS(13), 1,
      anon_sym_EQ,
    ACTIONS(15), 1,
      anon_sym_DOT,
    STATE(4), 2,
      sym_property_lookup,
      aux_sym_expression_repeat1,
    ACTIONS(9), 15,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      anon_sym_AND,
      aux_sym_expression_token1,
      aux_sym_expression_token2,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_EQ_TILDE,
  [31] = 4,
    ACTIONS(19), 1,
      anon_sym_EQ,
    ACTIONS(21), 1,
      anon_sym_DOT,
    STATE(3), 2,
      sym_property_lookup,
      aux_sym_expression_repeat1,
    ACTIONS(17), 16,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      anon_sym_IN,
      anon_sym_AND,
      aux_sym_expression_token1,
      aux_sym_expression_token2,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_EQ_TILDE,
  [60] = 5,
    ACTIONS(15), 1,
      anon_sym_DOT,
    ACTIONS(26), 1,
      anon_sym_IN,
    ACTIONS(28), 1,
      anon_sym_EQ,
    STATE(3), 2,
      sym_property_lookup,
      aux_sym_expression_repeat1,
    ACTIONS(24), 15,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      anon_sym_AND,
      aux_sym_expression_token1,
      aux_sym_expression_token2,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_EQ_TILDE,
  [91] = 2,
    ACTIONS(32), 1,
      anon_sym_EQ,
    ACTIONS(30), 18,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      anon_sym_IN,
      anon_sym_AND,
      aux_sym_expression_token1,
      aux_sym_expression_token2,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_EQ_TILDE,
      anon_sym_DOT,
  [115] = 3,
    ACTIONS(36), 1,
      anon_sym_LPAREN,
    ACTIONS(38), 1,
      anon_sym_EQ,
    ACTIONS(34), 17,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      anon_sym_IN,
      anon_sym_AND,
      aux_sym_expression_token1,
      aux_sym_expression_token2,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_EQ_TILDE,
      anon_sym_DOT,
  [141] = 2,
    ACTIONS(42), 1,
      anon_sym_EQ,
    ACTIONS(40), 17,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      anon_sym_IN,
      anon_sym_AND,
      aux_sym_expression_token1,
      aux_sym_expression_token2,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_EQ_TILDE,
      anon_sym_DOT,
  [164] = 2,
    ACTIONS(46), 1,
      anon_sym_EQ,
    ACTIONS(44), 17,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      anon_sym_IN,
      anon_sym_AND,
      aux_sym_expression_token1,
      aux_sym_expression_token2,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_EQ_TILDE,
      anon_sym_DOT,
  [187] = 2,
    ACTIONS(50), 1,
      anon_sym_EQ,
    ACTIONS(48), 17,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      anon_sym_IN,
      anon_sym_AND,
      aux_sym_expression_token1,
      aux_sym_expression_token2,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_EQ_TILDE,
      anon_sym_DOT,
  [210] = 2,
    ACTIONS(54), 1,
      anon_sym_EQ,
    ACTIONS(52), 17,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      anon_sym_IN,
      anon_sym_AND,
      aux_sym_expression_token1,
      aux_sym_expression_token2,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_EQ_TILDE,
      anon_sym_DOT,
  [233] = 2,
    ACTIONS(58), 1,
      anon_sym_EQ,
    ACTIONS(56), 17,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      anon_sym_IN,
      anon_sym_AND,
      aux_sym_expression_token1,
      aux_sym_expression_token2,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_EQ_TILDE,
      anon_sym_DOT,
  [256] = 12,
    ACTIONS(60), 1,
      anon_sym_NOT,
    ACTIONS(62), 1,
      anon_sym_DOLLAR,
    ACTIONS(64), 1,
      sym_decimal_integer_literal,
    ACTIONS(66), 1,
      anon_sym_SQUOTE,
    ACTIONS(68), 1,
      anon_sym_DQUOTE,
    ACTIONS(70), 1,
      sym_identifier,
    STATE(6), 1,
      sym__symbolic_name,
    STATE(46), 1,
      sym_expression,
    STATE(73), 1,
      sym__projection_item,
    STATE(105), 1,
      sym__projection_items,
    STATE(126), 1,
      sym_function_name,
    STATE(2), 6,
      sym__atom,
      sym_parameter,
      sym_function_invocation,
      sym__literal,
      sym_string_literal,
      sym_variable,
  [298] = 3,
    ACTIONS(74), 1,
      anon_sym_EQ_TILDE,
    ACTIONS(76), 1,
      anon_sym_EQ,
    ACTIONS(72), 14,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      anon_sym_AND,
      aux_sym_expression_token1,
      aux_sym_expression_token2,
      anon_sym_XOR,
      anon_sym_OR,
  [321] = 4,
    ACTIONS(74), 1,
      anon_sym_EQ_TILDE,
    ACTIONS(76), 1,
      anon_sym_EQ,
    ACTIONS(78), 1,
      anon_sym_OR,
    ACTIONS(72), 13,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      anon_sym_AND,
      aux_sym_expression_token1,
      aux_sym_expression_token2,
      anon_sym_XOR,
  [346] = 2,
    ACTIONS(82), 1,
      anon_sym_EQ,
    ACTIONS(80), 15,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      anon_sym_AND,
      aux_sym_expression_token1,
      aux_sym_expression_token2,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_EQ_TILDE,
  [367] = 6,
    ACTIONS(74), 1,
      anon_sym_EQ_TILDE,
    ACTIONS(76), 1,
      anon_sym_EQ,
    ACTIONS(78), 1,
      anon_sym_OR,
    ACTIONS(84), 1,
      anon_sym_AND,
    ACTIONS(86), 2,
      aux_sym_expression_token2,
      anon_sym_XOR,
    ACTIONS(72), 10,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      aux_sym_expression_token1,
  [396] = 6,
    ACTIONS(74), 1,
      anon_sym_EQ_TILDE,
    ACTIONS(76), 1,
      anon_sym_EQ,
    ACTIONS(78), 1,
      anon_sym_OR,
    ACTIONS(84), 1,
      anon_sym_AND,
    ACTIONS(86), 2,
      aux_sym_expression_token2,
      anon_sym_XOR,
    ACTIONS(24), 10,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      aux_sym_expression_token1,
  [425] = 2,
    ACTIONS(88), 1,
      anon_sym_EQ,
    ACTIONS(72), 15,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      anon_sym_AND,
      aux_sym_expression_token1,
      aux_sym_expression_token2,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_EQ_TILDE,
  [446] = 2,
    ACTIONS(88), 1,
      anon_sym_EQ,
    ACTIONS(72), 15,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      anon_sym_AND,
      aux_sym_expression_token1,
      aux_sym_expression_token2,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_EQ_TILDE,
  [467] = 11,
    ACTIONS(60), 1,
      anon_sym_NOT,
    ACTIONS(62), 1,
      anon_sym_DOLLAR,
    ACTIONS(64), 1,
      sym_decimal_integer_literal,
    ACTIONS(66), 1,
      anon_sym_SQUOTE,
    ACTIONS(68), 1,
      anon_sym_DQUOTE,
    ACTIONS(70), 1,
      sym_identifier,
    STATE(6), 1,
      sym__symbolic_name,
    STATE(46), 1,
      sym_expression,
    STATE(84), 1,
      sym__projection_item,
    STATE(126), 1,
      sym_function_name,
    STATE(2), 6,
      sym__atom,
      sym_parameter,
      sym_function_invocation,
      sym__literal,
      sym_string_literal,
      sym_variable,
  [506] = 4,
    ACTIONS(74), 1,
      anon_sym_EQ_TILDE,
    ACTIONS(76), 1,
      anon_sym_EQ,
    ACTIONS(78), 1,
      anon_sym_OR,
    ACTIONS(72), 13,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      anon_sym_AND,
      aux_sym_expression_token1,
      aux_sym_expression_token2,
      anon_sym_XOR,
  [531] = 2,
    ACTIONS(92), 1,
      anon_sym_EQ,
    ACTIONS(90), 15,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      anon_sym_AND,
      aux_sym_expression_token1,
      aux_sym_expression_token2,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_EQ_TILDE,
  [552] = 2,
    ACTIONS(96), 1,
      anon_sym_EQ,
    ACTIONS(94), 15,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      anon_sym_AND,
      aux_sym_expression_token1,
      aux_sym_expression_token2,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_EQ_TILDE,
  [573] = 10,
    ACTIONS(60), 1,
      anon_sym_NOT,
    ACTIONS(62), 1,
      anon_sym_DOLLAR,
    ACTIONS(64), 1,
      sym_decimal_integer_literal,
    ACTIONS(66), 1,
      anon_sym_SQUOTE,
    ACTIONS(68), 1,
      anon_sym_DQUOTE,
    ACTIONS(70), 1,
      sym_identifier,
    STATE(6), 1,
      sym__symbolic_name,
    STATE(14), 1,
      sym_expression,
    STATE(126), 1,
      sym_function_name,
    STATE(2), 6,
      sym__atom,
      sym_parameter,
      sym_function_invocation,
      sym__literal,
      sym_string_literal,
      sym_variable,
  [609] = 10,
    ACTIONS(60), 1,
      anon_sym_NOT,
    ACTIONS(62), 1,
      anon_sym_DOLLAR,
    ACTIONS(64), 1,
      sym_decimal_integer_literal,
    ACTIONS(66), 1,
      anon_sym_SQUOTE,
    ACTIONS(68), 1,
      anon_sym_DQUOTE,
    ACTIONS(70), 1,
      sym_identifier,
    STATE(6), 1,
      sym__symbolic_name,
    STATE(51), 1,
      sym_expression,
    STATE(126), 1,
      sym_function_name,
    STATE(2), 6,
      sym__atom,
      sym_parameter,
      sym_function_invocation,
      sym__literal,
      sym_string_literal,
      sym_variable,
  [645] = 10,
    ACTIONS(60), 1,
      anon_sym_NOT,
    ACTIONS(62), 1,
      anon_sym_DOLLAR,
    ACTIONS(64), 1,
      sym_decimal_integer_literal,
    ACTIONS(66), 1,
      anon_sym_SQUOTE,
    ACTIONS(68), 1,
      anon_sym_DQUOTE,
    ACTIONS(70), 1,
      sym_identifier,
    STATE(6), 1,
      sym__symbolic_name,
    STATE(21), 1,
      sym_expression,
    STATE(126), 1,
      sym_function_name,
    STATE(2), 6,
      sym__atom,
      sym_parameter,
      sym_function_invocation,
      sym__literal,
      sym_string_literal,
      sym_variable,
  [681] = 10,
    ACTIONS(60), 1,
      anon_sym_NOT,
    ACTIONS(62), 1,
      anon_sym_DOLLAR,
    ACTIONS(64), 1,
      sym_decimal_integer_literal,
    ACTIONS(66), 1,
      anon_sym_SQUOTE,
    ACTIONS(68), 1,
      anon_sym_DQUOTE,
    ACTIONS(70), 1,
      sym_identifier,
    STATE(6), 1,
      sym__symbolic_name,
    STATE(16), 1,
      sym_expression,
    STATE(126), 1,
      sym_function_name,
    STATE(2), 6,
      sym__atom,
      sym_parameter,
      sym_function_invocation,
      sym__literal,
      sym_string_literal,
      sym_variable,
  [717] = 10,
    ACTIONS(60), 1,
      anon_sym_NOT,
    ACTIONS(62), 1,
      anon_sym_DOLLAR,
    ACTIONS(64), 1,
      sym_decimal_integer_literal,
    ACTIONS(66), 1,
      anon_sym_SQUOTE,
    ACTIONS(68), 1,
      anon_sym_DQUOTE,
    ACTIONS(70), 1,
      sym_identifier,
    STATE(6), 1,
      sym__symbolic_name,
    STATE(19), 1,
      sym_expression,
    STATE(126), 1,
      sym_function_name,
    STATE(2), 6,
      sym__atom,
      sym_parameter,
      sym_function_invocation,
      sym__literal,
      sym_string_literal,
      sym_variable,
  [753] = 10,
    ACTIONS(60), 1,
      anon_sym_NOT,
    ACTIONS(62), 1,
      anon_sym_DOLLAR,
    ACTIONS(64), 1,
      sym_decimal_integer_literal,
    ACTIONS(66), 1,
      anon_sym_SQUOTE,
    ACTIONS(68), 1,
      anon_sym_DQUOTE,
    ACTIONS(70), 1,
      sym_identifier,
    STATE(6), 1,
      sym__symbolic_name,
    STATE(17), 1,
      sym_expression,
    STATE(126), 1,
      sym_function_name,
    STATE(2), 6,
      sym__atom,
      sym_parameter,
      sym_function_invocation,
      sym__literal,
      sym_string_literal,
      sym_variable,
  [789] = 10,
    ACTIONS(60), 1,
      anon_sym_NOT,
    ACTIONS(62), 1,
      anon_sym_DOLLAR,
    ACTIONS(64), 1,
      sym_decimal_integer_literal,
    ACTIONS(66), 1,
      anon_sym_SQUOTE,
    ACTIONS(68), 1,
      anon_sym_DQUOTE,
    ACTIONS(70), 1,
      sym_identifier,
    STATE(6), 1,
      sym__symbolic_name,
    STATE(47), 1,
      sym_expression,
    STATE(126), 1,
      sym_function_name,
    STATE(2), 6,
      sym__atom,
      sym_parameter,
      sym_function_invocation,
      sym__literal,
      sym_string_literal,
      sym_variable,
  [825] = 10,
    ACTIONS(60), 1,
      anon_sym_NOT,
    ACTIONS(62), 1,
      anon_sym_DOLLAR,
    ACTIONS(64), 1,
      sym_decimal_integer_literal,
    ACTIONS(66), 1,
      anon_sym_SQUOTE,
    ACTIONS(68), 1,
      anon_sym_DQUOTE,
    ACTIONS(70), 1,
      sym_identifier,
    STATE(6), 1,
      sym__symbolic_name,
    STATE(40), 1,
      sym_expression,
    STATE(126), 1,
      sym_function_name,
    STATE(2), 6,
      sym__atom,
      sym_parameter,
      sym_function_invocation,
      sym__literal,
      sym_string_literal,
      sym_variable,
  [861] = 10,
    ACTIONS(60), 1,
      anon_sym_NOT,
    ACTIONS(62), 1,
      anon_sym_DOLLAR,
    ACTIONS(64), 1,
      sym_decimal_integer_literal,
    ACTIONS(66), 1,
      anon_sym_SQUOTE,
    ACTIONS(68), 1,
      anon_sym_DQUOTE,
    ACTIONS(70), 1,
      sym_identifier,
    STATE(6), 1,
      sym__symbolic_name,
    STATE(43), 1,
      sym_expression,
    STATE(126), 1,
      sym_function_name,
    STATE(2), 6,
      sym__atom,
      sym_parameter,
      sym_function_invocation,
      sym__literal,
      sym_string_literal,
      sym_variable,
  [897] = 10,
    ACTIONS(60), 1,
      anon_sym_NOT,
    ACTIONS(62), 1,
      anon_sym_DOLLAR,
    ACTIONS(64), 1,
      sym_decimal_integer_literal,
    ACTIONS(66), 1,
      anon_sym_SQUOTE,
    ACTIONS(68), 1,
      anon_sym_DQUOTE,
    ACTIONS(70), 1,
      sym_identifier,
    STATE(6), 1,
      sym__symbolic_name,
    STATE(45), 1,
      sym_expression,
    STATE(126), 1,
      sym_function_name,
    STATE(2), 6,
      sym__atom,
      sym_parameter,
      sym_function_invocation,
      sym__literal,
      sym_string_literal,
      sym_variable,
  [933] = 10,
    ACTIONS(60), 1,
      anon_sym_NOT,
    ACTIONS(62), 1,
      anon_sym_DOLLAR,
    ACTIONS(64), 1,
      sym_decimal_integer_literal,
    ACTIONS(66), 1,
      anon_sym_SQUOTE,
    ACTIONS(68), 1,
      anon_sym_DQUOTE,
    ACTIONS(70), 1,
      sym_identifier,
    STATE(6), 1,
      sym__symbolic_name,
    STATE(13), 1,
      sym_expression,
    STATE(126), 1,
      sym_function_name,
    STATE(2), 6,
      sym__atom,
      sym_parameter,
      sym_function_invocation,
      sym__literal,
      sym_string_literal,
      sym_variable,
  [969] = 10,
    ACTIONS(60), 1,
      anon_sym_NOT,
    ACTIONS(62), 1,
      anon_sym_DOLLAR,
    ACTIONS(64), 1,
      sym_decimal_integer_literal,
    ACTIONS(66), 1,
      anon_sym_SQUOTE,
    ACTIONS(68), 1,
      anon_sym_DQUOTE,
    ACTIONS(70), 1,
      sym_identifier,
    STATE(6), 1,
      sym__symbolic_name,
    STATE(44), 1,
      sym_expression,
    STATE(126), 1,
      sym_function_name,
    STATE(2), 6,
      sym__atom,
      sym_parameter,
      sym_function_invocation,
      sym__literal,
      sym_string_literal,
      sym_variable,
  [1005] = 13,
    ACTIONS(98), 1,
      anon_sym_LPAREN,
    ACTIONS(100), 1,
      anon_sym_RPAREN,
    ACTIONS(102), 1,
      anon_sym_COLON,
    ACTIONS(104), 1,
      anon_sym_LBRACE,
    ACTIONS(106), 1,
      sym_identifier,
    STATE(37), 1,
      sym_node_pattern,
    STATE(57), 1,
      sym_variable,
    STATE(64), 1,
      sym_node_label,
    STATE(67), 1,
      sym_node_labels,
    STATE(74), 1,
      sym__symbolic_name,
    STATE(110), 1,
      sym_pattern_element,
    STATE(112), 1,
      sym_map_literal,
    STATE(119), 1,
      sym_properties,
  [1045] = 4,
    STATE(109), 1,
      sym__relationship_pattern,
    ACTIONS(110), 2,
      anon_sym_LT_DASH,
      anon_sym_DASH,
    STATE(39), 2,
      sym__pattern_element_chain,
      aux_sym_pattern_element_repeat1,
    ACTIONS(108), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_WHERE,
      anon_sym_CREATE,
      anon_sym_RETURN,
  [1066] = 4,
    STATE(109), 1,
      sym__relationship_pattern,
    ACTIONS(114), 2,
      anon_sym_LT_DASH,
      anon_sym_DASH,
    STATE(38), 2,
      sym__pattern_element_chain,
      aux_sym_pattern_element_repeat1,
    ACTIONS(112), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_WHERE,
      anon_sym_CREATE,
      anon_sym_RETURN,
  [1087] = 4,
    STATE(109), 1,
      sym__relationship_pattern,
    ACTIONS(110), 2,
      anon_sym_LT_DASH,
      anon_sym_DASH,
    STATE(38), 2,
      sym__pattern_element_chain,
      aux_sym_pattern_element_repeat1,
    ACTIONS(117), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_WHERE,
      anon_sym_CREATE,
      anon_sym_RETURN,
  [1108] = 9,
    ACTIONS(74), 1,
      anon_sym_EQ_TILDE,
    ACTIONS(76), 1,
      anon_sym_EQ,
    ACTIONS(78), 1,
      anon_sym_OR,
    ACTIONS(84), 1,
      anon_sym_AND,
    ACTIONS(119), 1,
      anon_sym_COMMA,
    ACTIONS(121), 1,
      anon_sym_RBRACE,
    ACTIONS(123), 1,
      aux_sym_expression_token1,
    STATE(83), 1,
      aux_sym_map_literal_repeat1,
    ACTIONS(86), 2,
      aux_sym_expression_token2,
      anon_sym_XOR,
  [1137] = 6,
    ACTIONS(3), 1,
      anon_sym_MATCH,
    ACTIONS(5), 1,
      anon_sym_CREATE,
    ACTIONS(7), 1,
      anon_sym_RETURN,
    STATE(100), 1,
      sym_return,
    STATE(54), 3,
      sym__updating_clause,
      sym_create,
      aux_sym__query_repeat2,
    STATE(59), 3,
      sym__reading_clause,
      sym_match,
      aux_sym__query_repeat1,
  [1160] = 10,
    ACTIONS(100), 1,
      anon_sym_RPAREN,
    ACTIONS(102), 1,
      anon_sym_COLON,
    ACTIONS(104), 1,
      anon_sym_LBRACE,
    ACTIONS(106), 1,
      sym_identifier,
    STATE(57), 1,
      sym_variable,
    STATE(64), 1,
      sym_node_label,
    STATE(67), 1,
      sym_node_labels,
    STATE(74), 1,
      sym__symbolic_name,
    STATE(112), 1,
      sym_map_literal,
    STATE(119), 1,
      sym_properties,
  [1191] = 9,
    ACTIONS(74), 1,
      anon_sym_EQ_TILDE,
    ACTIONS(76), 1,
      anon_sym_EQ,
    ACTIONS(78), 1,
      anon_sym_OR,
    ACTIONS(84), 1,
      anon_sym_AND,
    ACTIONS(123), 1,
      aux_sym_expression_token1,
    ACTIONS(125), 1,
      anon_sym_RPAREN,
    ACTIONS(127), 1,
      anon_sym_COMMA,
    STATE(92), 1,
      aux_sym_list_repeat1,
    ACTIONS(86), 2,
      aux_sym_expression_token2,
      anon_sym_XOR,
  [1220] = 7,
    ACTIONS(74), 1,
      anon_sym_EQ_TILDE,
    ACTIONS(76), 1,
      anon_sym_EQ,
    ACTIONS(78), 1,
      anon_sym_OR,
    ACTIONS(84), 1,
      anon_sym_AND,
    ACTIONS(123), 1,
      aux_sym_expression_token1,
    ACTIONS(86), 2,
      aux_sym_expression_token2,
      anon_sym_XOR,
    ACTIONS(129), 3,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
  [1245] = 7,
    ACTIONS(74), 1,
      anon_sym_EQ_TILDE,
    ACTIONS(76), 1,
      anon_sym_EQ,
    ACTIONS(78), 1,
      anon_sym_OR,
    ACTIONS(84), 1,
      anon_sym_AND,
    ACTIONS(123), 1,
      aux_sym_expression_token1,
    ACTIONS(86), 2,
      aux_sym_expression_token2,
      anon_sym_XOR,
    ACTIONS(131), 3,
      anon_sym_MATCH,
      anon_sym_CREATE,
      anon_sym_RETURN,
  [1270] = 7,
    ACTIONS(74), 1,
      anon_sym_EQ_TILDE,
    ACTIONS(76), 1,
      anon_sym_EQ,
    ACTIONS(78), 1,
      anon_sym_OR,
    ACTIONS(84), 1,
      anon_sym_AND,
    ACTIONS(123), 1,
      aux_sym_expression_token1,
    ACTIONS(86), 2,
      aux_sym_expression_token2,
      anon_sym_XOR,
    ACTIONS(133), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
  [1295] = 9,
    ACTIONS(74), 1,
      anon_sym_EQ_TILDE,
    ACTIONS(76), 1,
      anon_sym_EQ,
    ACTIONS(78), 1,
      anon_sym_OR,
    ACTIONS(84), 1,
      anon_sym_AND,
    ACTIONS(123), 1,
      aux_sym_expression_token1,
    ACTIONS(127), 1,
      anon_sym_COMMA,
    ACTIONS(135), 1,
      anon_sym_RBRACK,
    STATE(87), 1,
      aux_sym_list_repeat1,
    ACTIONS(86), 2,
      aux_sym_expression_token2,
      anon_sym_XOR,
  [1324] = 1,
    ACTIONS(137), 9,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_LT_DASH,
      anon_sym_DASH,
      anon_sym_WHERE,
      anon_sym_CREATE,
      anon_sym_RETURN,
  [1336] = 1,
    ACTIONS(139), 9,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_LT_DASH,
      anon_sym_DASH,
      anon_sym_WHERE,
      anon_sym_CREATE,
      anon_sym_RETURN,
  [1348] = 1,
    ACTIONS(141), 9,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_LT_DASH,
      anon_sym_DASH,
      anon_sym_WHERE,
      anon_sym_CREATE,
      anon_sym_RETURN,
  [1360] = 7,
    ACTIONS(74), 1,
      anon_sym_EQ_TILDE,
    ACTIONS(76), 1,
      anon_sym_EQ,
    ACTIONS(78), 1,
      anon_sym_OR,
    ACTIONS(84), 1,
      anon_sym_AND,
    ACTIONS(123), 1,
      aux_sym_expression_token1,
    ACTIONS(86), 2,
      aux_sym_expression_token2,
      anon_sym_XOR,
    ACTIONS(143), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1384] = 1,
    ACTIONS(145), 9,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_LT_DASH,
      anon_sym_DASH,
      anon_sym_WHERE,
      anon_sym_CREATE,
      anon_sym_RETURN,
  [1396] = 1,
    ACTIONS(147), 9,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_LT_DASH,
      anon_sym_DASH,
      anon_sym_WHERE,
      anon_sym_CREATE,
      anon_sym_RETURN,
  [1408] = 5,
    ACTIONS(5), 1,
      anon_sym_CREATE,
    ACTIONS(7), 1,
      anon_sym_RETURN,
    STATE(104), 1,
      sym_return,
    ACTIONS(149), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
    STATE(56), 3,
      sym__updating_clause,
      sym_create,
      aux_sym__query_repeat2,
  [1427] = 5,
    ACTIONS(5), 1,
      anon_sym_CREATE,
    ACTIONS(7), 1,
      anon_sym_RETURN,
    STATE(100), 1,
      sym_return,
    ACTIONS(151), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
    STATE(56), 3,
      sym__updating_clause,
      sym_create,
      aux_sym__query_repeat2,
  [1446] = 3,
    ACTIONS(155), 1,
      anon_sym_CREATE,
    ACTIONS(153), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RETURN,
    STATE(56), 3,
      sym__updating_clause,
      sym_create,
      aux_sym__query_repeat2,
  [1460] = 7,
    ACTIONS(102), 1,
      anon_sym_COLON,
    ACTIONS(104), 1,
      anon_sym_LBRACE,
    ACTIONS(158), 1,
      anon_sym_RPAREN,
    STATE(64), 1,
      sym_node_label,
    STATE(76), 1,
      sym_node_labels,
    STATE(112), 1,
      sym_map_literal,
    STATE(121), 1,
      sym_properties,
  [1482] = 1,
    ACTIONS(160), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_WHERE,
      anon_sym_CREATE,
      anon_sym_RETURN,
  [1492] = 3,
    ACTIONS(162), 1,
      anon_sym_MATCH,
    ACTIONS(165), 2,
      anon_sym_CREATE,
      anon_sym_RETURN,
    STATE(59), 3,
      sym__reading_clause,
      sym_match,
      aux_sym__query_repeat1,
  [1505] = 6,
    ACTIONS(106), 1,
      sym_identifier,
    ACTIONS(167), 1,
      anon_sym_RBRACK,
    ACTIONS(169), 1,
      anon_sym_COLON,
    STATE(74), 1,
      sym__symbolic_name,
    STATE(94), 1,
      sym_variable,
    STATE(114), 1,
      sym_relationship_types,
  [1524] = 3,
    ACTIONS(173), 1,
      anon_sym_COLON,
    ACTIONS(171), 2,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
    STATE(61), 2,
      sym_node_label,
      aux_sym_node_labels_repeat1,
  [1536] = 4,
    ACTIONS(176), 1,
      anon_sym_RBRACE,
    ACTIONS(178), 1,
      sym_identifier,
    STATE(125), 1,
      sym_property_key_name,
    STATE(5), 2,
      sym__schema_name,
      sym__symbolic_name,
  [1550] = 3,
    ACTIONS(182), 1,
      anon_sym_WHERE,
    STATE(88), 1,
      sym_where,
    ACTIONS(180), 3,
      anon_sym_MATCH,
      anon_sym_CREATE,
      anon_sym_RETURN,
  [1562] = 3,
    ACTIONS(102), 1,
      anon_sym_COLON,
    ACTIONS(184), 2,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
    STATE(66), 2,
      sym_node_label,
      aux_sym_node_labels_repeat1,
  [1574] = 4,
    ACTIONS(186), 1,
      anon_sym_COLON,
    ACTIONS(188), 1,
      sym_identifier,
    STATE(101), 1,
      sym_rel_type_name,
    STATE(107), 2,
      sym__schema_name,
      sym__symbolic_name,
  [1588] = 3,
    ACTIONS(102), 1,
      anon_sym_COLON,
    ACTIONS(190), 2,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
    STATE(61), 2,
      sym_node_label,
      aux_sym_node_labels_repeat1,
  [1600] = 4,
    ACTIONS(104), 1,
      anon_sym_LBRACE,
    ACTIONS(158), 1,
      anon_sym_RPAREN,
    STATE(112), 1,
      sym_map_literal,
    STATE(121), 1,
      sym_properties,
  [1613] = 4,
    ACTIONS(192), 1,
      anon_sym_DASH_GT,
    ACTIONS(194), 1,
      anon_sym_DASH,
    ACTIONS(196), 1,
      anon_sym_LBRACK,
    STATE(99), 1,
      sym_relationship_detail,
  [1626] = 3,
    ACTIONS(98), 1,
      anon_sym_LPAREN,
    STATE(37), 1,
      sym_node_pattern,
    STATE(79), 2,
      sym__pattern,
      sym_pattern_element,
  [1637] = 3,
    ACTIONS(198), 1,
      sym_identifier,
    STATE(85), 1,
      sym_label_name,
    STATE(86), 2,
      sym__schema_name,
      sym__symbolic_name,
  [1648] = 3,
    ACTIONS(98), 1,
      anon_sym_LPAREN,
    STATE(37), 1,
      sym_node_pattern,
    STATE(63), 2,
      sym__pattern,
      sym_pattern_element,
  [1659] = 3,
    ACTIONS(188), 1,
      sym_identifier,
    STATE(98), 1,
      sym_rel_type_name,
    STATE(107), 2,
      sym__schema_name,
      sym__symbolic_name,
  [1670] = 3,
    ACTIONS(202), 1,
      anon_sym_COMMA,
    STATE(82), 1,
      aux_sym__projection_items_repeat1,
    ACTIONS(200), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [1681] = 1,
    ACTIONS(34), 4,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COLON,
      anon_sym_LBRACE,
  [1688] = 3,
    ACTIONS(188), 1,
      sym_identifier,
    STATE(90), 1,
      sym_rel_type_name,
    STATE(107), 2,
      sym__schema_name,
      sym__symbolic_name,
  [1699] = 4,
    ACTIONS(104), 1,
      anon_sym_LBRACE,
    ACTIONS(204), 1,
      anon_sym_RPAREN,
    STATE(112), 1,
      sym_map_literal,
    STATE(120), 1,
      sym_properties,
  [1712] = 3,
    ACTIONS(206), 1,
      anon_sym_COMMA,
    STATE(77), 1,
      aux_sym_list_repeat1,
    ACTIONS(129), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1723] = 3,
    ACTIONS(211), 1,
      anon_sym_COMMA,
    STATE(78), 1,
      aux_sym__projection_items_repeat1,
    ACTIONS(209), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [1734] = 1,
    ACTIONS(214), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_CREATE,
      anon_sym_RETURN,
  [1741] = 3,
    ACTIONS(178), 1,
      sym_identifier,
    STATE(8), 1,
      sym_property_key_name,
    STATE(5), 2,
      sym__schema_name,
      sym__symbolic_name,
  [1752] = 3,
    ACTIONS(178), 1,
      sym_identifier,
    STATE(122), 1,
      sym_property_key_name,
    STATE(5), 2,
      sym__schema_name,
      sym__symbolic_name,
  [1763] = 3,
    ACTIONS(202), 1,
      anon_sym_COMMA,
    STATE(78), 1,
      aux_sym__projection_items_repeat1,
    ACTIONS(216), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [1774] = 3,
    ACTIONS(119), 1,
      anon_sym_COMMA,
    ACTIONS(218), 1,
      anon_sym_RBRACE,
    STATE(91), 1,
      aux_sym_map_literal_repeat1,
  [1784] = 1,
    ACTIONS(209), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
  [1790] = 1,
    ACTIONS(220), 3,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_LBRACE,
  [1796] = 1,
    ACTIONS(222), 3,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_LBRACE,
  [1802] = 3,
    ACTIONS(127), 1,
      anon_sym_COMMA,
    ACTIONS(224), 1,
      anon_sym_RBRACK,
    STATE(77), 1,
      aux_sym_list_repeat1,
  [1812] = 1,
    ACTIONS(226), 3,
      anon_sym_MATCH,
      anon_sym_CREATE,
      anon_sym_RETURN,
  [1818] = 3,
    ACTIONS(228), 1,
      anon_sym_RBRACK,
    ACTIONS(230), 1,
      anon_sym_PIPE,
    STATE(93), 1,
      aux_sym_relationship_types_repeat1,
  [1828] = 3,
    ACTIONS(230), 1,
      anon_sym_PIPE,
    ACTIONS(232), 1,
      anon_sym_RBRACK,
    STATE(89), 1,
      aux_sym_relationship_types_repeat1,
  [1838] = 3,
    ACTIONS(234), 1,
      anon_sym_COMMA,
    ACTIONS(237), 1,
      anon_sym_RBRACE,
    STATE(91), 1,
      aux_sym_map_literal_repeat1,
  [1848] = 3,
    ACTIONS(127), 1,
      anon_sym_COMMA,
    ACTIONS(239), 1,
      anon_sym_RPAREN,
    STATE(77), 1,
      aux_sym_list_repeat1,
  [1858] = 3,
    ACTIONS(241), 1,
      anon_sym_RBRACK,
    ACTIONS(243), 1,
      anon_sym_PIPE,
    STATE(93), 1,
      aux_sym_relationship_types_repeat1,
  [1868] = 3,
    ACTIONS(169), 1,
      anon_sym_COLON,
    ACTIONS(246), 1,
      anon_sym_RBRACK,
    STATE(118), 1,
      sym_relationship_types,
  [1878] = 2,
    ACTIONS(248), 1,
      sym_identifier,
    STATE(10), 1,
      sym__symbolic_name,
  [1885] = 2,
    ACTIONS(250), 1,
      anon_sym_LBRACK,
    STATE(23), 1,
      sym_list,
  [1892] = 2,
    ACTIONS(252), 1,
      anon_sym_DASH_GT,
    ACTIONS(254), 1,
      anon_sym_DASH,
  [1899] = 1,
    ACTIONS(256), 2,
      anon_sym_RBRACK,
      anon_sym_PIPE,
  [1904] = 2,
    ACTIONS(258), 1,
      anon_sym_DASH_GT,
    ACTIONS(260), 1,
      anon_sym_DASH,
  [1911] = 1,
    ACTIONS(149), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [1916] = 1,
    ACTIONS(241), 2,
      anon_sym_RBRACK,
      anon_sym_PIPE,
  [1921] = 2,
    ACTIONS(262), 1,
      ts_builtin_sym_end,
    ACTIONS(264), 1,
      anon_sym_SEMI,
  [1928] = 2,
    ACTIONS(266), 1,
      anon_sym_DASH_GT,
    ACTIONS(268), 1,
      anon_sym_DASH,
  [1935] = 1,
    ACTIONS(270), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [1940] = 1,
    ACTIONS(272), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [1945] = 2,
    ACTIONS(250), 1,
      anon_sym_LBRACK,
    STATE(18), 1,
      sym_list,
  [1952] = 1,
    ACTIONS(274), 2,
      anon_sym_RBRACK,
      anon_sym_PIPE,
  [1957] = 2,
    ACTIONS(276), 1,
      anon_sym_DASH_GT,
    ACTIONS(278), 1,
      anon_sym_DASH,
  [1964] = 2,
    ACTIONS(280), 1,
      anon_sym_LPAREN,
    STATE(52), 1,
      sym_node_pattern,
  [1971] = 1,
    ACTIONS(282), 1,
      anon_sym_RPAREN,
  [1975] = 1,
    ACTIONS(284), 1,
      aux_sym_string_literal_token2,
  [1979] = 1,
    ACTIONS(286), 1,
      anon_sym_RPAREN,
  [1983] = 1,
    ACTIONS(288), 1,
      aux_sym_string_literal_token1,
  [1987] = 1,
    ACTIONS(246), 1,
      anon_sym_RBRACK,
  [1991] = 1,
    ACTIONS(290), 1,
      anon_sym_SQUOTE,
  [1995] = 1,
    ACTIONS(292), 1,
      anon_sym_RPAREN,
  [1999] = 1,
    ACTIONS(290), 1,
      anon_sym_DQUOTE,
  [2003] = 1,
    ACTIONS(294), 1,
      anon_sym_RBRACK,
  [2007] = 1,
    ACTIONS(158), 1,
      anon_sym_RPAREN,
  [2011] = 1,
    ACTIONS(296), 1,
      anon_sym_RPAREN,
  [2015] = 1,
    ACTIONS(204), 1,
      anon_sym_RPAREN,
  [2019] = 1,
    ACTIONS(298), 1,
      anon_sym_COLON,
  [2023] = 1,
    ACTIONS(300), 1,
      anon_sym_RPAREN,
  [2027] = 1,
    ACTIONS(302), 1,
      anon_sym_RPAREN,
  [2031] = 1,
    ACTIONS(304), 1,
      anon_sym_COLON,
  [2035] = 1,
    ACTIONS(306), 1,
      anon_sym_LPAREN,
  [2039] = 1,
    ACTIONS(308), 1,
      ts_builtin_sym_end,
  [2043] = 1,
    ACTIONS(310), 1,
      ts_builtin_sym_end,
  [2047] = 1,
    ACTIONS(312), 1,
      anon_sym_LPAREN,
  [2051] = 1,
    ACTIONS(314), 1,
      anon_sym_LPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 31,
  [SMALL_STATE(4)] = 60,
  [SMALL_STATE(5)] = 91,
  [SMALL_STATE(6)] = 115,
  [SMALL_STATE(7)] = 141,
  [SMALL_STATE(8)] = 164,
  [SMALL_STATE(9)] = 187,
  [SMALL_STATE(10)] = 210,
  [SMALL_STATE(11)] = 233,
  [SMALL_STATE(12)] = 256,
  [SMALL_STATE(13)] = 298,
  [SMALL_STATE(14)] = 321,
  [SMALL_STATE(15)] = 346,
  [SMALL_STATE(16)] = 367,
  [SMALL_STATE(17)] = 396,
  [SMALL_STATE(18)] = 425,
  [SMALL_STATE(19)] = 446,
  [SMALL_STATE(20)] = 467,
  [SMALL_STATE(21)] = 506,
  [SMALL_STATE(22)] = 531,
  [SMALL_STATE(23)] = 552,
  [SMALL_STATE(24)] = 573,
  [SMALL_STATE(25)] = 609,
  [SMALL_STATE(26)] = 645,
  [SMALL_STATE(27)] = 681,
  [SMALL_STATE(28)] = 717,
  [SMALL_STATE(29)] = 753,
  [SMALL_STATE(30)] = 789,
  [SMALL_STATE(31)] = 825,
  [SMALL_STATE(32)] = 861,
  [SMALL_STATE(33)] = 897,
  [SMALL_STATE(34)] = 933,
  [SMALL_STATE(35)] = 969,
  [SMALL_STATE(36)] = 1005,
  [SMALL_STATE(37)] = 1045,
  [SMALL_STATE(38)] = 1066,
  [SMALL_STATE(39)] = 1087,
  [SMALL_STATE(40)] = 1108,
  [SMALL_STATE(41)] = 1137,
  [SMALL_STATE(42)] = 1160,
  [SMALL_STATE(43)] = 1191,
  [SMALL_STATE(44)] = 1220,
  [SMALL_STATE(45)] = 1245,
  [SMALL_STATE(46)] = 1270,
  [SMALL_STATE(47)] = 1295,
  [SMALL_STATE(48)] = 1324,
  [SMALL_STATE(49)] = 1336,
  [SMALL_STATE(50)] = 1348,
  [SMALL_STATE(51)] = 1360,
  [SMALL_STATE(52)] = 1384,
  [SMALL_STATE(53)] = 1396,
  [SMALL_STATE(54)] = 1408,
  [SMALL_STATE(55)] = 1427,
  [SMALL_STATE(56)] = 1446,
  [SMALL_STATE(57)] = 1460,
  [SMALL_STATE(58)] = 1482,
  [SMALL_STATE(59)] = 1492,
  [SMALL_STATE(60)] = 1505,
  [SMALL_STATE(61)] = 1524,
  [SMALL_STATE(62)] = 1536,
  [SMALL_STATE(63)] = 1550,
  [SMALL_STATE(64)] = 1562,
  [SMALL_STATE(65)] = 1574,
  [SMALL_STATE(66)] = 1588,
  [SMALL_STATE(67)] = 1600,
  [SMALL_STATE(68)] = 1613,
  [SMALL_STATE(69)] = 1626,
  [SMALL_STATE(70)] = 1637,
  [SMALL_STATE(71)] = 1648,
  [SMALL_STATE(72)] = 1659,
  [SMALL_STATE(73)] = 1670,
  [SMALL_STATE(74)] = 1681,
  [SMALL_STATE(75)] = 1688,
  [SMALL_STATE(76)] = 1699,
  [SMALL_STATE(77)] = 1712,
  [SMALL_STATE(78)] = 1723,
  [SMALL_STATE(79)] = 1734,
  [SMALL_STATE(80)] = 1741,
  [SMALL_STATE(81)] = 1752,
  [SMALL_STATE(82)] = 1763,
  [SMALL_STATE(83)] = 1774,
  [SMALL_STATE(84)] = 1784,
  [SMALL_STATE(85)] = 1790,
  [SMALL_STATE(86)] = 1796,
  [SMALL_STATE(87)] = 1802,
  [SMALL_STATE(88)] = 1812,
  [SMALL_STATE(89)] = 1818,
  [SMALL_STATE(90)] = 1828,
  [SMALL_STATE(91)] = 1838,
  [SMALL_STATE(92)] = 1848,
  [SMALL_STATE(93)] = 1858,
  [SMALL_STATE(94)] = 1868,
  [SMALL_STATE(95)] = 1878,
  [SMALL_STATE(96)] = 1885,
  [SMALL_STATE(97)] = 1892,
  [SMALL_STATE(98)] = 1899,
  [SMALL_STATE(99)] = 1904,
  [SMALL_STATE(100)] = 1911,
  [SMALL_STATE(101)] = 1916,
  [SMALL_STATE(102)] = 1921,
  [SMALL_STATE(103)] = 1928,
  [SMALL_STATE(104)] = 1935,
  [SMALL_STATE(105)] = 1940,
  [SMALL_STATE(106)] = 1945,
  [SMALL_STATE(107)] = 1952,
  [SMALL_STATE(108)] = 1957,
  [SMALL_STATE(109)] = 1964,
  [SMALL_STATE(110)] = 1971,
  [SMALL_STATE(111)] = 1975,
  [SMALL_STATE(112)] = 1979,
  [SMALL_STATE(113)] = 1983,
  [SMALL_STATE(114)] = 1987,
  [SMALL_STATE(115)] = 1991,
  [SMALL_STATE(116)] = 1995,
  [SMALL_STATE(117)] = 1999,
  [SMALL_STATE(118)] = 2003,
  [SMALL_STATE(119)] = 2007,
  [SMALL_STATE(120)] = 2011,
  [SMALL_STATE(121)] = 2015,
  [SMALL_STATE(122)] = 2019,
  [SMALL_STATE(123)] = 2023,
  [SMALL_STATE(124)] = 2027,
  [SMALL_STATE(125)] = 2031,
  [SMALL_STATE(126)] = 2035,
  [SMALL_STATE(127)] = 2039,
  [SMALL_STATE(128)] = 2043,
  [SMALL_STATE(129)] = 2047,
  [SMALL_STATE(130)] = 2051,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [13] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_expression_repeat1, 2),
  [19] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_expression_repeat1, 2),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_repeat1, 2), SHIFT_REPEAT(80),
  [24] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 2),
  [26] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [28] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 2),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_key_name, 1),
  [32] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property_key_name, 1),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 1),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_name, 1),
  [38] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 1),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_invocation, 5),
  [42] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_invocation, 5),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_lookup, 2),
  [46] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property_lookup, 2),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 3),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 3),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 2),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter, 2),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_invocation, 4),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_invocation, 4),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 3),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [76] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 3),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 3),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 4),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 4),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 4),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 4),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern_element, 1),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pattern_element_repeat1, 2),
  [114] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_element_repeat1, 2), SHIFT_REPEAT(68),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern_element, 2),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_where, 2),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__projection_item, 1),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_pattern, 2),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_pattern, 4),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_pattern, 5),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_map_literal_repeat1, 4),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__pattern_element_chain, 2),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_pattern, 3),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__query, 2),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__query, 1),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__query_repeat2, 2),
  [155] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__query_repeat2, 2), SHIFT_REPEAT(69),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern_element, 3),
  [162] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__query_repeat1, 2), SHIFT_REPEAT(71),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__query_repeat1, 2),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_node_labels_repeat1, 2),
  [173] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_node_labels_repeat1, 2), SHIFT_REPEAT(70),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_match, 2),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_labels, 1),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_labels, 2),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [194] = {.entry = {.count = 1, .reusable = false}}, SHIFT(130),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__projection_items, 1),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [206] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2), SHIFT_REPEAT(35),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__projection_items_repeat1, 2),
  [211] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__projection_items_repeat1, 2), SHIFT_REPEAT(20),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_create, 2),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__projection_items, 2),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_label, 2),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label_name, 1),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_match, 3),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_relationship_types, 3),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_relationship_types, 2),
  [234] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_map_literal_repeat1, 2), SHIFT_REPEAT(81),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_map_literal_repeat1, 2),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_relationship_types_repeat1, 2),
  [243] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_relationship_types_repeat1, 2), SHIFT_REPEAT(65),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_relationship_detail, 2),
  [254] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_relationship_detail, 2),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_relationship_types_repeat1, 3),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [260] = {.entry = {.count = 1, .reusable = false}}, SHIFT(129),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cypher, 1),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_relationship_detail, 4),
  [268] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_relationship_detail, 4),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__query, 3),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return, 2),
  [274] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rel_type_name, 1),
  [276] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_relationship_detail, 3),
  [278] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_relationship_detail, 3),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [286] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_properties, 1),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [292] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map_literal, 5),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [300] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map_literal, 6),
  [302] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map_literal, 2),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [308] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cypher, 2),
  [310] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [312] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__relationship_pattern, 3),
  [314] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__relationship_pattern, 2),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_cypher(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
