#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 127
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 75
#define ALIAS_COUNT 0
#define TOKEN_COUNT 31
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_SEMI = 1,
  anon_sym_MATCH = 2,
  anon_sym_LPAREN = 3,
  anon_sym_RPAREN = 4,
  anon_sym_LT_DASH = 5,
  anon_sym_DASH_GT = 6,
  anon_sym_DASH = 7,
  anon_sym_LBRACK = 8,
  anon_sym_RBRACK = 9,
  anon_sym_COLON = 10,
  anon_sym_PIPE = 11,
  anon_sym_LBRACE = 12,
  anon_sym_COMMA = 13,
  anon_sym_RBRACE = 14,
  anon_sym_WHERE = 15,
  anon_sym_CREATE = 16,
  anon_sym_RETURN = 17,
  anon_sym_IN = 18,
  anon_sym_AND = 19,
  aux_sym_expression_token1 = 20,
  aux_sym_expression_token2 = 21,
  anon_sym_XOR = 22,
  anon_sym_OR = 23,
  anon_sym_NOT = 24,
  anon_sym_EQ_TILDE = 25,
  anon_sym_DOT = 26,
  sym_decimal_integer_literal = 27,
  anon_sym_SQUOTE = 28,
  aux_sym_string_literal_token1 = 29,
  sym_identifier = 30,
  sym_cypher = 31,
  sym__query = 32,
  sym__reading_clause = 33,
  sym_match = 34,
  sym__pattern = 35,
  sym_pattern_element = 36,
  sym__pattern_element_chain = 37,
  sym__relationship_pattern = 38,
  sym_relationship_detail = 39,
  sym_relationship_types = 40,
  sym_rel_type_name = 41,
  sym_node_pattern = 42,
  sym_node_labels = 43,
  sym_node_label = 44,
  sym_label_name = 45,
  sym_properties = 46,
  sym_map_literal = 47,
  sym_where = 48,
  sym__updating_clause = 49,
  sym_create = 50,
  sym_return = 51,
  sym__projection_items = 52,
  sym__projection_item = 53,
  sym_expression = 54,
  sym_list = 55,
  sym_property_lookup = 56,
  sym_property_key_name = 57,
  sym__schema_name = 58,
  sym__atom = 59,
  sym_function_invocation = 60,
  sym_function_name = 61,
  sym__literal = 62,
  sym_string_literal = 63,
  sym_variable = 64,
  sym__symbolic_name = 65,
  aux_sym__query_repeat1 = 66,
  aux_sym__query_repeat2 = 67,
  aux_sym_pattern_element_repeat1 = 68,
  aux_sym_relationship_types_repeat1 = 69,
  aux_sym_node_labels_repeat1 = 70,
  aux_sym_map_literal_repeat1 = 71,
  aux_sym__projection_items_repeat1 = 72,
  aux_sym_expression_repeat1 = 73,
  aux_sym_list_repeat1 = 74,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SEMI] = ";",
  [anon_sym_MATCH] = "MATCH",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LT_DASH] = "<-",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_DASH] = "-",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_COLON] = ":",
  [anon_sym_PIPE] = "|",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACE] = "}",
  [anon_sym_WHERE] = "WHERE",
  [anon_sym_CREATE] = "CREATE",
  [anon_sym_RETURN] = "RETURN",
  [anon_sym_IN] = "IN",
  [anon_sym_AND] = "AND",
  [aux_sym_expression_token1] = "expression_token1",
  [aux_sym_expression_token2] = "expression_token2",
  [anon_sym_XOR] = "XOR",
  [anon_sym_OR] = "OR",
  [anon_sym_NOT] = "NOT",
  [anon_sym_EQ_TILDE] = "=~",
  [anon_sym_DOT] = ".",
  [sym_decimal_integer_literal] = "decimal_integer_literal",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_string_literal_token1] = "string_literal_token1",
  [sym_identifier] = "identifier",
  [sym_cypher] = "cypher",
  [sym__query] = "_query",
  [sym__reading_clause] = "_reading_clause",
  [sym_match] = "match",
  [sym__pattern] = "_pattern",
  [sym_pattern_element] = "pattern_element",
  [sym__pattern_element_chain] = "_pattern_element_chain",
  [sym__relationship_pattern] = "_relationship_pattern",
  [sym_relationship_detail] = "relationship_detail",
  [sym_relationship_types] = "relationship_types",
  [sym_rel_type_name] = "rel_type_name",
  [sym_node_pattern] = "node_pattern",
  [sym_node_labels] = "node_labels",
  [sym_node_label] = "node_label",
  [sym_label_name] = "label_name",
  [sym_properties] = "properties",
  [sym_map_literal] = "map_literal",
  [sym_where] = "where",
  [sym__updating_clause] = "_updating_clause",
  [sym_create] = "create",
  [sym_return] = "return",
  [sym__projection_items] = "_projection_items",
  [sym__projection_item] = "_projection_item",
  [sym_expression] = "expression",
  [sym_list] = "list",
  [sym_property_lookup] = "property_lookup",
  [sym_property_key_name] = "property_key_name",
  [sym__schema_name] = "_schema_name",
  [sym__atom] = "_atom",
  [sym_function_invocation] = "function_invocation",
  [sym_function_name] = "function_name",
  [sym__literal] = "_literal",
  [sym_string_literal] = "string_literal",
  [sym_variable] = "variable",
  [sym__symbolic_name] = "_symbolic_name",
  [aux_sym__query_repeat1] = "_query_repeat1",
  [aux_sym__query_repeat2] = "_query_repeat2",
  [aux_sym_pattern_element_repeat1] = "pattern_element_repeat1",
  [aux_sym_relationship_types_repeat1] = "relationship_types_repeat1",
  [aux_sym_node_labels_repeat1] = "node_labels_repeat1",
  [aux_sym_map_literal_repeat1] = "map_literal_repeat1",
  [aux_sym__projection_items_repeat1] = "_projection_items_repeat1",
  [aux_sym_expression_repeat1] = "expression_repeat1",
  [aux_sym_list_repeat1] = "list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_MATCH] = anon_sym_MATCH,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LT_DASH] = anon_sym_LT_DASH,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_WHERE] = anon_sym_WHERE,
  [anon_sym_CREATE] = anon_sym_CREATE,
  [anon_sym_RETURN] = anon_sym_RETURN,
  [anon_sym_IN] = anon_sym_IN,
  [anon_sym_AND] = anon_sym_AND,
  [aux_sym_expression_token1] = aux_sym_expression_token1,
  [aux_sym_expression_token2] = aux_sym_expression_token2,
  [anon_sym_XOR] = anon_sym_XOR,
  [anon_sym_OR] = anon_sym_OR,
  [anon_sym_NOT] = anon_sym_NOT,
  [anon_sym_EQ_TILDE] = anon_sym_EQ_TILDE,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_decimal_integer_literal] = sym_decimal_integer_literal,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_string_literal_token1] = aux_sym_string_literal_token1,
  [sym_identifier] = sym_identifier,
  [sym_cypher] = sym_cypher,
  [sym__query] = sym__query,
  [sym__reading_clause] = sym__reading_clause,
  [sym_match] = sym_match,
  [sym__pattern] = sym__pattern,
  [sym_pattern_element] = sym_pattern_element,
  [sym__pattern_element_chain] = sym__pattern_element_chain,
  [sym__relationship_pattern] = sym__relationship_pattern,
  [sym_relationship_detail] = sym_relationship_detail,
  [sym_relationship_types] = sym_relationship_types,
  [sym_rel_type_name] = sym_rel_type_name,
  [sym_node_pattern] = sym_node_pattern,
  [sym_node_labels] = sym_node_labels,
  [sym_node_label] = sym_node_label,
  [sym_label_name] = sym_label_name,
  [sym_properties] = sym_properties,
  [sym_map_literal] = sym_map_literal,
  [sym_where] = sym_where,
  [sym__updating_clause] = sym__updating_clause,
  [sym_create] = sym_create,
  [sym_return] = sym_return,
  [sym__projection_items] = sym__projection_items,
  [sym__projection_item] = sym__projection_item,
  [sym_expression] = sym_expression,
  [sym_list] = sym_list,
  [sym_property_lookup] = sym_property_lookup,
  [sym_property_key_name] = sym_property_key_name,
  [sym__schema_name] = sym__schema_name,
  [sym__atom] = sym__atom,
  [sym_function_invocation] = sym_function_invocation,
  [sym_function_name] = sym_function_name,
  [sym__literal] = sym__literal,
  [sym_string_literal] = sym_string_literal,
  [sym_variable] = sym_variable,
  [sym__symbolic_name] = sym__symbolic_name,
  [aux_sym__query_repeat1] = aux_sym__query_repeat1,
  [aux_sym__query_repeat2] = aux_sym__query_repeat2,
  [aux_sym_pattern_element_repeat1] = aux_sym_pattern_element_repeat1,
  [aux_sym_relationship_types_repeat1] = aux_sym_relationship_types_repeat1,
  [aux_sym_node_labels_repeat1] = aux_sym_node_labels_repeat1,
  [aux_sym_map_literal_repeat1] = aux_sym_map_literal_repeat1,
  [aux_sym__projection_items_repeat1] = aux_sym__projection_items_repeat1,
  [aux_sym_expression_repeat1] = aux_sym_expression_repeat1,
  [aux_sym_list_repeat1] = aux_sym_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_MATCH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_WHERE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CREATE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RETURN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_IN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_expression_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_expression_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_XOR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_OR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_NOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_decimal_integer_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_cypher] = {
    .visible = true,
    .named = true,
  },
  [sym__query] = {
    .visible = false,
    .named = true,
  },
  [sym__reading_clause] = {
    .visible = false,
    .named = true,
  },
  [sym_match] = {
    .visible = true,
    .named = true,
  },
  [sym__pattern] = {
    .visible = false,
    .named = true,
  },
  [sym_pattern_element] = {
    .visible = true,
    .named = true,
  },
  [sym__pattern_element_chain] = {
    .visible = false,
    .named = true,
  },
  [sym__relationship_pattern] = {
    .visible = false,
    .named = true,
  },
  [sym_relationship_detail] = {
    .visible = true,
    .named = true,
  },
  [sym_relationship_types] = {
    .visible = true,
    .named = true,
  },
  [sym_rel_type_name] = {
    .visible = true,
    .named = true,
  },
  [sym_node_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_node_labels] = {
    .visible = true,
    .named = true,
  },
  [sym_node_label] = {
    .visible = true,
    .named = true,
  },
  [sym_label_name] = {
    .visible = true,
    .named = true,
  },
  [sym_properties] = {
    .visible = true,
    .named = true,
  },
  [sym_map_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_where] = {
    .visible = true,
    .named = true,
  },
  [sym__updating_clause] = {
    .visible = false,
    .named = true,
  },
  [sym_create] = {
    .visible = true,
    .named = true,
  },
  [sym_return] = {
    .visible = true,
    .named = true,
  },
  [sym__projection_items] = {
    .visible = false,
    .named = true,
  },
  [sym__projection_item] = {
    .visible = false,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_property_lookup] = {
    .visible = true,
    .named = true,
  },
  [sym_property_key_name] = {
    .visible = true,
    .named = true,
  },
  [sym__schema_name] = {
    .visible = false,
    .named = true,
  },
  [sym__atom] = {
    .visible = false,
    .named = true,
  },
  [sym_function_invocation] = {
    .visible = true,
    .named = true,
  },
  [sym_function_name] = {
    .visible = true,
    .named = true,
  },
  [sym__literal] = {
    .visible = false,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym__symbolic_name] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__query_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__query_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pattern_element_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_relationship_types_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_node_labels_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_map_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__projection_items_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(33);
      if (lookahead == '\'') ADVANCE(64);
      if (lookahead == '(') ADVANCE(36);
      if (lookahead == ')') ADVANCE(37);
      if (lookahead == '+') ADVANCE(54);
      if (lookahead == ',') ADVANCE(47);
      if (lookahead == '-') ADVANCE(41);
      if (lookahead == '.') ADVANCE(61);
      if (lookahead == '0') ADVANCE(62);
      if (lookahead == ':') ADVANCE(44);
      if (lookahead == ';') ADVANCE(34);
      if (lookahead == '<') ADVANCE(3);
      if (lookahead == '=') ADVANCE(30);
      if (lookahead == 'A') ADVANCE(15);
      if (lookahead == 'C') ADVANCE(22);
      if (lookahead == 'I') ADVANCE(16);
      if (lookahead == 'M') ADVANCE(4);
      if (lookahead == 'N') ADVANCE(18);
      if (lookahead == 'O') ADVANCE(20);
      if (lookahead == 'R') ADVANCE(10);
      if (lookahead == 'W') ADVANCE(14);
      if (lookahead == 'X') ADVANCE(19);
      if (lookahead == '[') ADVANCE(42);
      if (lookahead == ']') ADVANCE(43);
      if (lookahead == '{') ADVANCE(46);
      if (lookahead == '|') ADVANCE(45);
      if (lookahead == '}') ADVANCE(48);
      if (lookahead == '%' ||
          ('*' <= lookahead && lookahead <= '/')) ADVANCE(55);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(63);
      END_STATE();
    case 1:
      if (lookahead == '\'') ADVANCE(64);
      if (lookahead == '-') ADVANCE(41);
      if (lookahead == '0') ADVANCE(62);
      if (lookahead == 'N') ADVANCE(67);
      if (lookahead == '[') ADVANCE(42);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(63);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 2:
      if (lookahead == '(') ADVANCE(36);
      if (lookahead == ')') ADVANCE(37);
      if (lookahead == ':') ADVANCE(44);
      if (lookahead == ']') ADVANCE(43);
      if (lookahead == '{') ADVANCE(46);
      if (lookahead == '}') ADVANCE(48);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 3:
      if (lookahead == '-') ADVANCE(38);
      END_STATE();
    case 4:
      if (lookahead == 'A') ADVANCE(25);
      END_STATE();
    case 5:
      if (lookahead == 'A') ADVANCE(28);
      END_STATE();
    case 6:
      if (lookahead == 'C') ADVANCE(13);
      END_STATE();
    case 7:
      if (lookahead == 'D') ADVANCE(53);
      END_STATE();
    case 8:
      if (lookahead == 'E') ADVANCE(49);
      END_STATE();
    case 9:
      if (lookahead == 'E') ADVANCE(50);
      END_STATE();
    case 10:
      if (lookahead == 'E') ADVANCE(27);
      END_STATE();
    case 11:
      if (lookahead == 'E') ADVANCE(24);
      END_STATE();
    case 12:
      if (lookahead == 'E') ADVANCE(5);
      END_STATE();
    case 13:
      if (lookahead == 'H') ADVANCE(35);
      END_STATE();
    case 14:
      if (lookahead == 'H') ADVANCE(11);
      END_STATE();
    case 15:
      if (lookahead == 'N') ADVANCE(7);
      END_STATE();
    case 16:
      if (lookahead == 'N') ADVANCE(52);
      END_STATE();
    case 17:
      if (lookahead == 'N') ADVANCE(51);
      END_STATE();
    case 18:
      if (lookahead == 'O') ADVANCE(26);
      END_STATE();
    case 19:
      if (lookahead == 'O') ADVANCE(21);
      END_STATE();
    case 20:
      if (lookahead == 'R') ADVANCE(57);
      END_STATE();
    case 21:
      if (lookahead == 'R') ADVANCE(56);
      END_STATE();
    case 22:
      if (lookahead == 'R') ADVANCE(12);
      END_STATE();
    case 23:
      if (lookahead == 'R') ADVANCE(17);
      END_STATE();
    case 24:
      if (lookahead == 'R') ADVANCE(8);
      END_STATE();
    case 25:
      if (lookahead == 'T') ADVANCE(6);
      END_STATE();
    case 26:
      if (lookahead == 'T') ADVANCE(58);
      END_STATE();
    case 27:
      if (lookahead == 'T') ADVANCE(29);
      END_STATE();
    case 28:
      if (lookahead == 'T') ADVANCE(9);
      END_STATE();
    case 29:
      if (lookahead == 'U') ADVANCE(23);
      END_STATE();
    case 30:
      if (lookahead == '~') ADVANCE(60);
      END_STATE();
    case 31:
      if (eof) ADVANCE(33);
      if (lookahead == '(') ADVANCE(36);
      if (lookahead == ')') ADVANCE(37);
      if (lookahead == ',') ADVANCE(47);
      if (lookahead == '.') ADVANCE(61);
      if (lookahead == ':') ADVANCE(44);
      if (lookahead == ';') ADVANCE(34);
      if (lookahead == '=') ADVANCE(30);
      if (lookahead == 'A') ADVANCE(15);
      if (lookahead == 'C') ADVANCE(22);
      if (lookahead == 'I') ADVANCE(16);
      if (lookahead == 'M') ADVANCE(4);
      if (lookahead == 'O') ADVANCE(20);
      if (lookahead == 'R') ADVANCE(10);
      if (lookahead == 'X') ADVANCE(19);
      if (lookahead == ']') ADVANCE(43);
      if (lookahead == '}') ADVANCE(48);
      if (('+' <= lookahead && lookahead <= '-')) ADVANCE(54);
      if (lookahead == '%' ||
          ('*' <= lookahead && lookahead <= '/')) ADVANCE(55);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(31)
      END_STATE();
    case 32:
      if (eof) ADVANCE(33);
      if (lookahead == ')') ADVANCE(37);
      if (lookahead == '-') ADVANCE(40);
      if (lookahead == ';') ADVANCE(34);
      if (lookahead == '<') ADVANCE(3);
      if (lookahead == 'C') ADVANCE(22);
      if (lookahead == 'M') ADVANCE(4);
      if (lookahead == 'R') ADVANCE(10);
      if (lookahead == 'W') ADVANCE(14);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(32)
      END_STATE();
    case 33:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_MATCH);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_LT_DASH);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '>') ADVANCE(39);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_WHERE);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_CREATE);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_RETURN);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_IN);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_AND);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym_expression_token1);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_expression_token2);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_XOR);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_OR);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_NOT);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_NOT);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_EQ_TILDE);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_decimal_integer_literal);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_decimal_integer_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(65);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(66);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'O') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'T') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 31},
  [3] = {.lex_state = 31},
  [4] = {.lex_state = 31},
  [5] = {.lex_state = 31},
  [6] = {.lex_state = 31},
  [7] = {.lex_state = 31},
  [8] = {.lex_state = 31},
  [9] = {.lex_state = 31},
  [10] = {.lex_state = 31},
  [11] = {.lex_state = 31},
  [12] = {.lex_state = 31},
  [13] = {.lex_state = 31},
  [14] = {.lex_state = 31},
  [15] = {.lex_state = 31},
  [16] = {.lex_state = 31},
  [17] = {.lex_state = 31},
  [18] = {.lex_state = 31},
  [19] = {.lex_state = 31},
  [20] = {.lex_state = 31},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 32},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 32},
  [35] = {.lex_state = 32},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 2},
  [41] = {.lex_state = 32},
  [42] = {.lex_state = 31},
  [43] = {.lex_state = 32},
  [44] = {.lex_state = 31},
  [45] = {.lex_state = 32},
  [46] = {.lex_state = 32},
  [47] = {.lex_state = 31},
  [48] = {.lex_state = 31},
  [49] = {.lex_state = 31},
  [50] = {.lex_state = 32},
  [51] = {.lex_state = 31},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 31},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 2},
  [60] = {.lex_state = 2},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 2},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 1},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 2},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 2},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 2},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 2},
  [80] = {.lex_state = 2},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 1},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 1},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 1},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 1},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 65},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_MATCH] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LT_DASH] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_WHERE] = ACTIONS(1),
    [anon_sym_CREATE] = ACTIONS(1),
    [anon_sym_RETURN] = ACTIONS(1),
    [anon_sym_IN] = ACTIONS(1),
    [anon_sym_AND] = ACTIONS(1),
    [aux_sym_expression_token1] = ACTIONS(1),
    [aux_sym_expression_token2] = ACTIONS(1),
    [anon_sym_XOR] = ACTIONS(1),
    [anon_sym_OR] = ACTIONS(1),
    [anon_sym_NOT] = ACTIONS(1),
    [anon_sym_EQ_TILDE] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_decimal_integer_literal] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
  },
  [1] = {
    [sym_cypher] = STATE(124),
    [sym__query] = STATE(100),
    [sym__reading_clause] = STATE(39),
    [sym_match] = STATE(39),
    [sym__updating_clause] = STATE(54),
    [sym_create] = STATE(54),
    [sym_return] = STATE(100),
    [aux_sym__query_repeat1] = STATE(39),
    [aux_sym__query_repeat2] = STATE(54),
    [anon_sym_MATCH] = ACTIONS(3),
    [anon_sym_CREATE] = ACTIONS(5),
    [anon_sym_RETURN] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(11), 1,
      anon_sym_IN,
    ACTIONS(13), 1,
      anon_sym_DOT,
    STATE(4), 2,
      sym_property_lookup,
      aux_sym_expression_repeat1,
    ACTIONS(9), 15,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      anon_sym_AND,
      aux_sym_expression_token1,
      aux_sym_expression_token2,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_EQ_TILDE,
  [28] = 3,
    ACTIONS(17), 1,
      anon_sym_DOT,
    STATE(3), 2,
      sym_property_lookup,
      aux_sym_expression_repeat1,
    ACTIONS(15), 16,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      anon_sym_IN,
      anon_sym_AND,
      aux_sym_expression_token1,
      aux_sym_expression_token2,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_EQ_TILDE,
  [54] = 4,
    ACTIONS(13), 1,
      anon_sym_DOT,
    ACTIONS(22), 1,
      anon_sym_IN,
    STATE(3), 2,
      sym_property_lookup,
      aux_sym_expression_repeat1,
    ACTIONS(20), 15,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      anon_sym_AND,
      aux_sym_expression_token1,
      aux_sym_expression_token2,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_EQ_TILDE,
  [82] = 2,
    ACTIONS(26), 1,
      anon_sym_LPAREN,
    ACTIONS(24), 17,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      anon_sym_IN,
      anon_sym_AND,
      aux_sym_expression_token1,
      aux_sym_expression_token2,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_EQ_TILDE,
      anon_sym_DOT,
  [105] = 1,
    ACTIONS(28), 18,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      anon_sym_IN,
      anon_sym_AND,
      aux_sym_expression_token1,
      aux_sym_expression_token2,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_EQ_TILDE,
      anon_sym_DOT,
  [126] = 1,
    ACTIONS(30), 17,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      anon_sym_IN,
      anon_sym_AND,
      aux_sym_expression_token1,
      aux_sym_expression_token2,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_EQ_TILDE,
      anon_sym_DOT,
  [146] = 1,
    ACTIONS(32), 17,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      anon_sym_IN,
      anon_sym_AND,
      aux_sym_expression_token1,
      aux_sym_expression_token2,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_EQ_TILDE,
      anon_sym_DOT,
  [166] = 1,
    ACTIONS(34), 17,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      anon_sym_IN,
      anon_sym_AND,
      aux_sym_expression_token1,
      aux_sym_expression_token2,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_EQ_TILDE,
      anon_sym_DOT,
  [186] = 1,
    ACTIONS(36), 17,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      anon_sym_IN,
      anon_sym_AND,
      aux_sym_expression_token1,
      aux_sym_expression_token2,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_EQ_TILDE,
      anon_sym_DOT,
  [206] = 5,
    ACTIONS(40), 1,
      anon_sym_AND,
    ACTIONS(44), 1,
      anon_sym_OR,
    ACTIONS(46), 1,
      anon_sym_EQ_TILDE,
    ACTIONS(42), 2,
      aux_sym_expression_token2,
      anon_sym_XOR,
    ACTIONS(38), 10,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      aux_sym_expression_token1,
  [232] = 2,
    ACTIONS(46), 1,
      anon_sym_EQ_TILDE,
    ACTIONS(38), 14,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      anon_sym_AND,
      aux_sym_expression_token1,
      aux_sym_expression_token2,
      anon_sym_XOR,
      anon_sym_OR,
  [252] = 1,
    ACTIONS(38), 15,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      anon_sym_AND,
      aux_sym_expression_token1,
      aux_sym_expression_token2,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_EQ_TILDE,
  [270] = 5,
    ACTIONS(40), 1,
      anon_sym_AND,
    ACTIONS(44), 1,
      anon_sym_OR,
    ACTIONS(46), 1,
      anon_sym_EQ_TILDE,
    ACTIONS(42), 2,
      aux_sym_expression_token2,
      anon_sym_XOR,
    ACTIONS(20), 10,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      aux_sym_expression_token1,
  [296] = 1,
    ACTIONS(48), 15,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      anon_sym_AND,
      aux_sym_expression_token1,
      aux_sym_expression_token2,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_EQ_TILDE,
  [314] = 3,
    ACTIONS(44), 1,
      anon_sym_OR,
    ACTIONS(46), 1,
      anon_sym_EQ_TILDE,
    ACTIONS(38), 13,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      anon_sym_AND,
      aux_sym_expression_token1,
      aux_sym_expression_token2,
      anon_sym_XOR,
  [336] = 1,
    ACTIONS(50), 15,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      anon_sym_AND,
      aux_sym_expression_token1,
      aux_sym_expression_token2,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_EQ_TILDE,
  [354] = 3,
    ACTIONS(44), 1,
      anon_sym_OR,
    ACTIONS(46), 1,
      anon_sym_EQ_TILDE,
    ACTIONS(38), 13,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      anon_sym_AND,
      aux_sym_expression_token1,
      aux_sym_expression_token2,
      anon_sym_XOR,
  [376] = 1,
    ACTIONS(38), 15,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      anon_sym_AND,
      aux_sym_expression_token1,
      aux_sym_expression_token2,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_EQ_TILDE,
  [394] = 1,
    ACTIONS(52), 15,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      anon_sym_AND,
      aux_sym_expression_token1,
      aux_sym_expression_token2,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_EQ_TILDE,
  [412] = 10,
    ACTIONS(54), 1,
      anon_sym_NOT,
    ACTIONS(56), 1,
      sym_decimal_integer_literal,
    ACTIONS(58), 1,
      anon_sym_SQUOTE,
    ACTIONS(60), 1,
      sym_identifier,
    STATE(5), 1,
      sym__symbolic_name,
    STATE(49), 1,
      sym_expression,
    STATE(72), 1,
      sym__projection_item,
    STATE(107), 1,
      sym__projection_items,
    STATE(116), 1,
      sym_function_name,
    STATE(2), 5,
      sym__atom,
      sym_function_invocation,
      sym__literal,
      sym_string_literal,
      sym_variable,
  [447] = 9,
    ACTIONS(54), 1,
      anon_sym_NOT,
    ACTIONS(56), 1,
      sym_decimal_integer_literal,
    ACTIONS(58), 1,
      anon_sym_SQUOTE,
    ACTIONS(60), 1,
      sym_identifier,
    STATE(5), 1,
      sym__symbolic_name,
    STATE(49), 1,
      sym_expression,
    STATE(87), 1,
      sym__projection_item,
    STATE(116), 1,
      sym_function_name,
    STATE(2), 5,
      sym__atom,
      sym_function_invocation,
      sym__literal,
      sym_string_literal,
      sym_variable,
  [479] = 13,
    ACTIONS(62), 1,
      anon_sym_LPAREN,
    ACTIONS(64), 1,
      anon_sym_RPAREN,
    ACTIONS(66), 1,
      anon_sym_COLON,
    ACTIONS(68), 1,
      anon_sym_LBRACE,
    ACTIONS(70), 1,
      sym_identifier,
    STATE(25), 1,
      sym_node_pattern,
    STATE(57), 1,
      sym_variable,
    STATE(64), 1,
      sym_node_label,
    STATE(66), 1,
      sym_node_labels,
    STATE(73), 1,
      sym__symbolic_name,
    STATE(110), 1,
      sym_map_literal,
    STATE(111), 1,
      sym_properties,
    STATE(125), 1,
      sym_pattern_element,
  [519] = 8,
    ACTIONS(54), 1,
      anon_sym_NOT,
    ACTIONS(56), 1,
      sym_decimal_integer_literal,
    ACTIONS(58), 1,
      anon_sym_SQUOTE,
    ACTIONS(60), 1,
      sym_identifier,
    STATE(5), 1,
      sym__symbolic_name,
    STATE(19), 1,
      sym_expression,
    STATE(116), 1,
      sym_function_name,
    STATE(2), 5,
      sym__atom,
      sym_function_invocation,
      sym__literal,
      sym_string_literal,
      sym_variable,
  [548] = 4,
    STATE(95), 1,
      sym__relationship_pattern,
    ACTIONS(74), 2,
      anon_sym_LT_DASH,
      anon_sym_DASH,
    STATE(34), 2,
      sym__pattern_element_chain,
      aux_sym_pattern_element_repeat1,
    ACTIONS(72), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_WHERE,
      anon_sym_CREATE,
      anon_sym_RETURN,
  [569] = 8,
    ACTIONS(54), 1,
      anon_sym_NOT,
    ACTIONS(56), 1,
      sym_decimal_integer_literal,
    ACTIONS(58), 1,
      anon_sym_SQUOTE,
    ACTIONS(60), 1,
      sym_identifier,
    STATE(5), 1,
      sym__symbolic_name,
    STATE(47), 1,
      sym_expression,
    STATE(116), 1,
      sym_function_name,
    STATE(2), 5,
      sym__atom,
      sym_function_invocation,
      sym__literal,
      sym_string_literal,
      sym_variable,
  [598] = 8,
    ACTIONS(54), 1,
      anon_sym_NOT,
    ACTIONS(56), 1,
      sym_decimal_integer_literal,
    ACTIONS(58), 1,
      anon_sym_SQUOTE,
    ACTIONS(60), 1,
      sym_identifier,
    STATE(5), 1,
      sym__symbolic_name,
    STATE(12), 1,
      sym_expression,
    STATE(116), 1,
      sym_function_name,
    STATE(2), 5,
      sym__atom,
      sym_function_invocation,
      sym__literal,
      sym_string_literal,
      sym_variable,
  [627] = 8,
    ACTIONS(54), 1,
      anon_sym_NOT,
    ACTIONS(56), 1,
      sym_decimal_integer_literal,
    ACTIONS(58), 1,
      anon_sym_SQUOTE,
    ACTIONS(60), 1,
      sym_identifier,
    STATE(5), 1,
      sym__symbolic_name,
    STATE(16), 1,
      sym_expression,
    STATE(116), 1,
      sym_function_name,
    STATE(2), 5,
      sym__atom,
      sym_function_invocation,
      sym__literal,
      sym_string_literal,
      sym_variable,
  [656] = 8,
    ACTIONS(54), 1,
      anon_sym_NOT,
    ACTIONS(56), 1,
      sym_decimal_integer_literal,
    ACTIONS(58), 1,
      anon_sym_SQUOTE,
    ACTIONS(60), 1,
      sym_identifier,
    STATE(5), 1,
      sym__symbolic_name,
    STATE(11), 1,
      sym_expression,
    STATE(116), 1,
      sym_function_name,
    STATE(2), 5,
      sym__atom,
      sym_function_invocation,
      sym__literal,
      sym_string_literal,
      sym_variable,
  [685] = 8,
    ACTIONS(54), 1,
      anon_sym_NOT,
    ACTIONS(56), 1,
      sym_decimal_integer_literal,
    ACTIONS(58), 1,
      anon_sym_SQUOTE,
    ACTIONS(60), 1,
      sym_identifier,
    STATE(5), 1,
      sym__symbolic_name,
    STATE(42), 1,
      sym_expression,
    STATE(116), 1,
      sym_function_name,
    STATE(2), 5,
      sym__atom,
      sym_function_invocation,
      sym__literal,
      sym_string_literal,
      sym_variable,
  [714] = 8,
    ACTIONS(54), 1,
      anon_sym_NOT,
    ACTIONS(56), 1,
      sym_decimal_integer_literal,
    ACTIONS(58), 1,
      anon_sym_SQUOTE,
    ACTIONS(60), 1,
      sym_identifier,
    STATE(5), 1,
      sym__symbolic_name,
    STATE(44), 1,
      sym_expression,
    STATE(116), 1,
      sym_function_name,
    STATE(2), 5,
      sym__atom,
      sym_function_invocation,
      sym__literal,
      sym_string_literal,
      sym_variable,
  [743] = 8,
    ACTIONS(54), 1,
      anon_sym_NOT,
    ACTIONS(56), 1,
      sym_decimal_integer_literal,
    ACTIONS(58), 1,
      anon_sym_SQUOTE,
    ACTIONS(60), 1,
      sym_identifier,
    STATE(5), 1,
      sym__symbolic_name,
    STATE(53), 1,
      sym_expression,
    STATE(116), 1,
      sym_function_name,
    STATE(2), 5,
      sym__atom,
      sym_function_invocation,
      sym__literal,
      sym_string_literal,
      sym_variable,
  [772] = 8,
    ACTIONS(54), 1,
      anon_sym_NOT,
    ACTIONS(56), 1,
      sym_decimal_integer_literal,
    ACTIONS(58), 1,
      anon_sym_SQUOTE,
    ACTIONS(60), 1,
      sym_identifier,
    STATE(5), 1,
      sym__symbolic_name,
    STATE(51), 1,
      sym_expression,
    STATE(116), 1,
      sym_function_name,
    STATE(2), 5,
      sym__atom,
      sym_function_invocation,
      sym__literal,
      sym_string_literal,
      sym_variable,
  [801] = 4,
    STATE(95), 1,
      sym__relationship_pattern,
    ACTIONS(74), 2,
      anon_sym_LT_DASH,
      anon_sym_DASH,
    STATE(35), 2,
      sym__pattern_element_chain,
      aux_sym_pattern_element_repeat1,
    ACTIONS(76), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_WHERE,
      anon_sym_CREATE,
      anon_sym_RETURN,
  [822] = 4,
    STATE(95), 1,
      sym__relationship_pattern,
    ACTIONS(80), 2,
      anon_sym_LT_DASH,
      anon_sym_DASH,
    STATE(35), 2,
      sym__pattern_element_chain,
      aux_sym_pattern_element_repeat1,
    ACTIONS(78), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_WHERE,
      anon_sym_CREATE,
      anon_sym_RETURN,
  [843] = 8,
    ACTIONS(54), 1,
      anon_sym_NOT,
    ACTIONS(56), 1,
      sym_decimal_integer_literal,
    ACTIONS(58), 1,
      anon_sym_SQUOTE,
    ACTIONS(60), 1,
      sym_identifier,
    STATE(5), 1,
      sym__symbolic_name,
    STATE(14), 1,
      sym_expression,
    STATE(116), 1,
      sym_function_name,
    STATE(2), 5,
      sym__atom,
      sym_function_invocation,
      sym__literal,
      sym_string_literal,
      sym_variable,
  [872] = 8,
    ACTIONS(54), 1,
      anon_sym_NOT,
    ACTIONS(56), 1,
      sym_decimal_integer_literal,
    ACTIONS(58), 1,
      anon_sym_SQUOTE,
    ACTIONS(60), 1,
      sym_identifier,
    STATE(5), 1,
      sym__symbolic_name,
    STATE(48), 1,
      sym_expression,
    STATE(116), 1,
      sym_function_name,
    STATE(2), 5,
      sym__atom,
      sym_function_invocation,
      sym__literal,
      sym_string_literal,
      sym_variable,
  [901] = 8,
    ACTIONS(54), 1,
      anon_sym_NOT,
    ACTIONS(56), 1,
      sym_decimal_integer_literal,
    ACTIONS(58), 1,
      anon_sym_SQUOTE,
    ACTIONS(60), 1,
      sym_identifier,
    STATE(5), 1,
      sym__symbolic_name,
    STATE(18), 1,
      sym_expression,
    STATE(116), 1,
      sym_function_name,
    STATE(2), 5,
      sym__atom,
      sym_function_invocation,
      sym__literal,
      sym_string_literal,
      sym_variable,
  [930] = 6,
    ACTIONS(3), 1,
      anon_sym_MATCH,
    ACTIONS(5), 1,
      anon_sym_CREATE,
    ACTIONS(7), 1,
      anon_sym_RETURN,
    STATE(98), 1,
      sym_return,
    STATE(52), 3,
      sym__updating_clause,
      sym_create,
      aux_sym__query_repeat2,
    STATE(58), 3,
      sym__reading_clause,
      sym_match,
      aux_sym__query_repeat1,
  [953] = 10,
    ACTIONS(64), 1,
      anon_sym_RPAREN,
    ACTIONS(66), 1,
      anon_sym_COLON,
    ACTIONS(68), 1,
      anon_sym_LBRACE,
    ACTIONS(70), 1,
      sym_identifier,
    STATE(57), 1,
      sym_variable,
    STATE(64), 1,
      sym_node_label,
    STATE(66), 1,
      sym_node_labels,
    STATE(73), 1,
      sym__symbolic_name,
    STATE(110), 1,
      sym_map_literal,
    STATE(111), 1,
      sym_properties,
  [984] = 1,
    ACTIONS(83), 9,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_LT_DASH,
      anon_sym_DASH,
      anon_sym_WHERE,
      anon_sym_CREATE,
      anon_sym_RETURN,
  [996] = 8,
    ACTIONS(40), 1,
      anon_sym_AND,
    ACTIONS(44), 1,
      anon_sym_OR,
    ACTIONS(46), 1,
      anon_sym_EQ_TILDE,
    ACTIONS(85), 1,
      anon_sym_COMMA,
    ACTIONS(87), 1,
      anon_sym_RBRACE,
    ACTIONS(89), 1,
      aux_sym_expression_token1,
    STATE(82), 1,
      aux_sym_map_literal_repeat1,
    ACTIONS(42), 2,
      aux_sym_expression_token2,
      anon_sym_XOR,
  [1022] = 1,
    ACTIONS(91), 9,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_LT_DASH,
      anon_sym_DASH,
      anon_sym_WHERE,
      anon_sym_CREATE,
      anon_sym_RETURN,
  [1034] = 6,
    ACTIONS(40), 1,
      anon_sym_AND,
    ACTIONS(44), 1,
      anon_sym_OR,
    ACTIONS(46), 1,
      anon_sym_EQ_TILDE,
    ACTIONS(89), 1,
      aux_sym_expression_token1,
    ACTIONS(42), 2,
      aux_sym_expression_token2,
      anon_sym_XOR,
    ACTIONS(93), 3,
      anon_sym_MATCH,
      anon_sym_CREATE,
      anon_sym_RETURN,
  [1056] = 1,
    ACTIONS(95), 9,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_LT_DASH,
      anon_sym_DASH,
      anon_sym_WHERE,
      anon_sym_CREATE,
      anon_sym_RETURN,
  [1068] = 1,
    ACTIONS(97), 9,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_LT_DASH,
      anon_sym_DASH,
      anon_sym_WHERE,
      anon_sym_CREATE,
      anon_sym_RETURN,
  [1080] = 6,
    ACTIONS(40), 1,
      anon_sym_AND,
    ACTIONS(44), 1,
      anon_sym_OR,
    ACTIONS(46), 1,
      anon_sym_EQ_TILDE,
    ACTIONS(89), 1,
      aux_sym_expression_token1,
    ACTIONS(42), 2,
      aux_sym_expression_token2,
      anon_sym_XOR,
    ACTIONS(99), 3,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
  [1102] = 8,
    ACTIONS(40), 1,
      anon_sym_AND,
    ACTIONS(44), 1,
      anon_sym_OR,
    ACTIONS(46), 1,
      anon_sym_EQ_TILDE,
    ACTIONS(89), 1,
      aux_sym_expression_token1,
    ACTIONS(101), 1,
      anon_sym_RBRACK,
    ACTIONS(103), 1,
      anon_sym_COMMA,
    STATE(88), 1,
      aux_sym_list_repeat1,
    ACTIONS(42), 2,
      aux_sym_expression_token2,
      anon_sym_XOR,
  [1128] = 6,
    ACTIONS(40), 1,
      anon_sym_AND,
    ACTIONS(44), 1,
      anon_sym_OR,
    ACTIONS(46), 1,
      anon_sym_EQ_TILDE,
    ACTIONS(89), 1,
      aux_sym_expression_token1,
    ACTIONS(42), 2,
      aux_sym_expression_token2,
      anon_sym_XOR,
    ACTIONS(105), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
  [1150] = 1,
    ACTIONS(107), 9,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_LT_DASH,
      anon_sym_DASH,
      anon_sym_WHERE,
      anon_sym_CREATE,
      anon_sym_RETURN,
  [1162] = 8,
    ACTIONS(40), 1,
      anon_sym_AND,
    ACTIONS(44), 1,
      anon_sym_OR,
    ACTIONS(46), 1,
      anon_sym_EQ_TILDE,
    ACTIONS(89), 1,
      aux_sym_expression_token1,
    ACTIONS(103), 1,
      anon_sym_COMMA,
    ACTIONS(109), 1,
      anon_sym_RPAREN,
    STATE(92), 1,
      aux_sym_list_repeat1,
    ACTIONS(42), 2,
      aux_sym_expression_token2,
      anon_sym_XOR,
  [1188] = 5,
    ACTIONS(5), 1,
      anon_sym_CREATE,
    ACTIONS(7), 1,
      anon_sym_RETURN,
    STATE(102), 1,
      sym_return,
    ACTIONS(111), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
    STATE(55), 3,
      sym__updating_clause,
      sym_create,
      aux_sym__query_repeat2,
  [1207] = 6,
    ACTIONS(40), 1,
      anon_sym_AND,
    ACTIONS(44), 1,
      anon_sym_OR,
    ACTIONS(46), 1,
      anon_sym_EQ_TILDE,
    ACTIONS(89), 1,
      aux_sym_expression_token1,
    ACTIONS(42), 2,
      aux_sym_expression_token2,
      anon_sym_XOR,
    ACTIONS(113), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1228] = 5,
    ACTIONS(5), 1,
      anon_sym_CREATE,
    ACTIONS(7), 1,
      anon_sym_RETURN,
    STATE(98), 1,
      sym_return,
    ACTIONS(115), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
    STATE(55), 3,
      sym__updating_clause,
      sym_create,
      aux_sym__query_repeat2,
  [1247] = 3,
    ACTIONS(119), 1,
      anon_sym_CREATE,
    ACTIONS(117), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RETURN,
    STATE(55), 3,
      sym__updating_clause,
      sym_create,
      aux_sym__query_repeat2,
  [1261] = 1,
    ACTIONS(122), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_WHERE,
      anon_sym_CREATE,
      anon_sym_RETURN,
  [1271] = 7,
    ACTIONS(66), 1,
      anon_sym_COLON,
    ACTIONS(68), 1,
      anon_sym_LBRACE,
    ACTIONS(124), 1,
      anon_sym_RPAREN,
    STATE(64), 1,
      sym_node_label,
    STATE(77), 1,
      sym_node_labels,
    STATE(110), 1,
      sym_map_literal,
    STATE(123), 1,
      sym_properties,
  [1293] = 3,
    ACTIONS(126), 1,
      anon_sym_MATCH,
    ACTIONS(129), 2,
      anon_sym_CREATE,
      anon_sym_RETURN,
    STATE(58), 3,
      sym__reading_clause,
      sym_match,
      aux_sym__query_repeat1,
  [1306] = 6,
    ACTIONS(70), 1,
      sym_identifier,
    ACTIONS(131), 1,
      anon_sym_RBRACK,
    ACTIONS(133), 1,
      anon_sym_COLON,
    STATE(73), 1,
      sym__symbolic_name,
    STATE(93), 1,
      sym_variable,
    STATE(115), 1,
      sym_relationship_types,
  [1325] = 4,
    ACTIONS(135), 1,
      anon_sym_RBRACE,
    ACTIONS(137), 1,
      sym_identifier,
    STATE(121), 1,
      sym_property_key_name,
    STATE(6), 2,
      sym__schema_name,
      sym__symbolic_name,
  [1339] = 3,
    ACTIONS(141), 1,
      anon_sym_WHERE,
    STATE(86), 1,
      sym_where,
    ACTIONS(139), 3,
      anon_sym_MATCH,
      anon_sym_CREATE,
      anon_sym_RETURN,
  [1351] = 4,
    ACTIONS(143), 1,
      anon_sym_COLON,
    ACTIONS(145), 1,
      sym_identifier,
    STATE(99), 1,
      sym_rel_type_name,
    STATE(103), 2,
      sym__schema_name,
      sym__symbolic_name,
  [1365] = 3,
    ACTIONS(149), 1,
      anon_sym_COLON,
    ACTIONS(147), 2,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
    STATE(63), 2,
      sym_node_label,
      aux_sym_node_labels_repeat1,
  [1377] = 3,
    ACTIONS(66), 1,
      anon_sym_COLON,
    ACTIONS(152), 2,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
    STATE(65), 2,
      sym_node_label,
      aux_sym_node_labels_repeat1,
  [1389] = 3,
    ACTIONS(66), 1,
      anon_sym_COLON,
    ACTIONS(154), 2,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
    STATE(63), 2,
      sym_node_label,
      aux_sym_node_labels_repeat1,
  [1401] = 4,
    ACTIONS(68), 1,
      anon_sym_LBRACE,
    ACTIONS(124), 1,
      anon_sym_RPAREN,
    STATE(110), 1,
      sym_map_literal,
    STATE(123), 1,
      sym_properties,
  [1414] = 4,
    ACTIONS(156), 1,
      anon_sym_DASH_GT,
    ACTIONS(158), 1,
      anon_sym_DASH,
    ACTIONS(160), 1,
      anon_sym_LBRACK,
    STATE(97), 1,
      sym_relationship_detail,
  [1427] = 3,
    ACTIONS(62), 1,
      anon_sym_LPAREN,
    STATE(25), 1,
      sym_node_pattern,
    STATE(78), 2,
      sym__pattern,
      sym_pattern_element,
  [1438] = 3,
    ACTIONS(145), 1,
      sym_identifier,
    STATE(90), 1,
      sym_rel_type_name,
    STATE(103), 2,
      sym__schema_name,
      sym__symbolic_name,
  [1449] = 3,
    ACTIONS(62), 1,
      anon_sym_LPAREN,
    STATE(25), 1,
      sym_node_pattern,
    STATE(61), 2,
      sym__pattern,
      sym_pattern_element,
  [1460] = 3,
    ACTIONS(145), 1,
      sym_identifier,
    STATE(96), 1,
      sym_rel_type_name,
    STATE(103), 2,
      sym__schema_name,
      sym__symbolic_name,
  [1471] = 3,
    ACTIONS(164), 1,
      anon_sym_COMMA,
    STATE(81), 1,
      aux_sym__projection_items_repeat1,
    ACTIONS(162), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [1482] = 1,
    ACTIONS(24), 4,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COLON,
      anon_sym_LBRACE,
  [1489] = 3,
    ACTIONS(168), 1,
      anon_sym_COMMA,
    STATE(74), 1,
      aux_sym__projection_items_repeat1,
    ACTIONS(166), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [1500] = 3,
    ACTIONS(171), 1,
      sym_identifier,
    STATE(83), 1,
      sym_label_name,
    STATE(84), 2,
      sym__schema_name,
      sym__symbolic_name,
  [1511] = 3,
    ACTIONS(173), 1,
      anon_sym_COMMA,
    STATE(76), 1,
      aux_sym_list_repeat1,
    ACTIONS(99), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1522] = 4,
    ACTIONS(68), 1,
      anon_sym_LBRACE,
    ACTIONS(176), 1,
      anon_sym_RPAREN,
    STATE(108), 1,
      sym_properties,
    STATE(110), 1,
      sym_map_literal,
  [1535] = 1,
    ACTIONS(178), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_CREATE,
      anon_sym_RETURN,
  [1542] = 3,
    ACTIONS(137), 1,
      sym_identifier,
    STATE(7), 1,
      sym_property_key_name,
    STATE(6), 2,
      sym__schema_name,
      sym__symbolic_name,
  [1553] = 3,
    ACTIONS(137), 1,
      sym_identifier,
    STATE(118), 1,
      sym_property_key_name,
    STATE(6), 2,
      sym__schema_name,
      sym__symbolic_name,
  [1564] = 3,
    ACTIONS(164), 1,
      anon_sym_COMMA,
    STATE(74), 1,
      aux_sym__projection_items_repeat1,
    ACTIONS(180), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [1575] = 3,
    ACTIONS(85), 1,
      anon_sym_COMMA,
    ACTIONS(182), 1,
      anon_sym_RBRACE,
    STATE(89), 1,
      aux_sym_map_literal_repeat1,
  [1585] = 1,
    ACTIONS(184), 3,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_LBRACE,
  [1591] = 1,
    ACTIONS(186), 3,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_LBRACE,
  [1597] = 3,
    ACTIONS(188), 1,
      anon_sym_RBRACK,
    ACTIONS(190), 1,
      anon_sym_PIPE,
    STATE(91), 1,
      aux_sym_relationship_types_repeat1,
  [1607] = 1,
    ACTIONS(192), 3,
      anon_sym_MATCH,
      anon_sym_CREATE,
      anon_sym_RETURN,
  [1613] = 1,
    ACTIONS(166), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
  [1619] = 3,
    ACTIONS(103), 1,
      anon_sym_COMMA,
    ACTIONS(194), 1,
      anon_sym_RBRACK,
    STATE(76), 1,
      aux_sym_list_repeat1,
  [1629] = 3,
    ACTIONS(196), 1,
      anon_sym_COMMA,
    ACTIONS(199), 1,
      anon_sym_RBRACE,
    STATE(89), 1,
      aux_sym_map_literal_repeat1,
  [1639] = 3,
    ACTIONS(190), 1,
      anon_sym_PIPE,
    ACTIONS(201), 1,
      anon_sym_RBRACK,
    STATE(85), 1,
      aux_sym_relationship_types_repeat1,
  [1649] = 3,
    ACTIONS(203), 1,
      anon_sym_RBRACK,
    ACTIONS(205), 1,
      anon_sym_PIPE,
    STATE(91), 1,
      aux_sym_relationship_types_repeat1,
  [1659] = 3,
    ACTIONS(103), 1,
      anon_sym_COMMA,
    ACTIONS(208), 1,
      anon_sym_RPAREN,
    STATE(76), 1,
      aux_sym_list_repeat1,
  [1669] = 3,
    ACTIONS(133), 1,
      anon_sym_COLON,
    ACTIONS(210), 1,
      anon_sym_RBRACK,
    STATE(114), 1,
      sym_relationship_types,
  [1679] = 2,
    ACTIONS(212), 1,
      anon_sym_LBRACK,
    STATE(17), 1,
      sym_list,
  [1686] = 2,
    ACTIONS(214), 1,
      anon_sym_LPAREN,
    STATE(45), 1,
      sym_node_pattern,
  [1693] = 1,
    ACTIONS(216), 2,
      anon_sym_RBRACK,
      anon_sym_PIPE,
  [1698] = 2,
    ACTIONS(218), 1,
      anon_sym_DASH_GT,
    ACTIONS(220), 1,
      anon_sym_DASH,
  [1705] = 1,
    ACTIONS(111), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [1710] = 1,
    ACTIONS(203), 2,
      anon_sym_RBRACK,
      anon_sym_PIPE,
  [1715] = 2,
    ACTIONS(222), 1,
      ts_builtin_sym_end,
    ACTIONS(224), 1,
      anon_sym_SEMI,
  [1722] = 2,
    ACTIONS(226), 1,
      anon_sym_DASH_GT,
    ACTIONS(228), 1,
      anon_sym_DASH,
  [1729] = 1,
    ACTIONS(230), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [1734] = 1,
    ACTIONS(232), 2,
      anon_sym_RBRACK,
      anon_sym_PIPE,
  [1739] = 2,
    ACTIONS(234), 1,
      anon_sym_DASH_GT,
    ACTIONS(236), 1,
      anon_sym_DASH,
  [1746] = 2,
    ACTIONS(212), 1,
      anon_sym_LBRACK,
    STATE(13), 1,
      sym_list,
  [1753] = 2,
    ACTIONS(238), 1,
      anon_sym_DASH_GT,
    ACTIONS(240), 1,
      anon_sym_DASH,
  [1760] = 1,
    ACTIONS(242), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [1765] = 1,
    ACTIONS(244), 1,
      anon_sym_RPAREN,
  [1769] = 1,
    ACTIONS(246), 1,
      aux_sym_string_literal_token1,
  [1773] = 1,
    ACTIONS(248), 1,
      anon_sym_RPAREN,
  [1777] = 1,
    ACTIONS(124), 1,
      anon_sym_RPAREN,
  [1781] = 1,
    ACTIONS(250), 1,
      anon_sym_RPAREN,
  [1785] = 1,
    ACTIONS(252), 1,
      anon_sym_SQUOTE,
  [1789] = 1,
    ACTIONS(254), 1,
      anon_sym_RBRACK,
  [1793] = 1,
    ACTIONS(210), 1,
      anon_sym_RBRACK,
  [1797] = 1,
    ACTIONS(256), 1,
      anon_sym_LPAREN,
  [1801] = 1,
    ACTIONS(258), 1,
      ts_builtin_sym_end,
  [1805] = 1,
    ACTIONS(260), 1,
      anon_sym_COLON,
  [1809] = 1,
    ACTIONS(262), 1,
      anon_sym_RPAREN,
  [1813] = 1,
    ACTIONS(264), 1,
      anon_sym_RPAREN,
  [1817] = 1,
    ACTIONS(266), 1,
      anon_sym_COLON,
  [1821] = 1,
    ACTIONS(268), 1,
      anon_sym_LPAREN,
  [1825] = 1,
    ACTIONS(176), 1,
      anon_sym_RPAREN,
  [1829] = 1,
    ACTIONS(270), 1,
      ts_builtin_sym_end,
  [1833] = 1,
    ACTIONS(272), 1,
      anon_sym_RPAREN,
  [1837] = 1,
    ACTIONS(274), 1,
      anon_sym_LPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 28,
  [SMALL_STATE(4)] = 54,
  [SMALL_STATE(5)] = 82,
  [SMALL_STATE(6)] = 105,
  [SMALL_STATE(7)] = 126,
  [SMALL_STATE(8)] = 146,
  [SMALL_STATE(9)] = 166,
  [SMALL_STATE(10)] = 186,
  [SMALL_STATE(11)] = 206,
  [SMALL_STATE(12)] = 232,
  [SMALL_STATE(13)] = 252,
  [SMALL_STATE(14)] = 270,
  [SMALL_STATE(15)] = 296,
  [SMALL_STATE(16)] = 314,
  [SMALL_STATE(17)] = 336,
  [SMALL_STATE(18)] = 354,
  [SMALL_STATE(19)] = 376,
  [SMALL_STATE(20)] = 394,
  [SMALL_STATE(21)] = 412,
  [SMALL_STATE(22)] = 447,
  [SMALL_STATE(23)] = 479,
  [SMALL_STATE(24)] = 519,
  [SMALL_STATE(25)] = 548,
  [SMALL_STATE(26)] = 569,
  [SMALL_STATE(27)] = 598,
  [SMALL_STATE(28)] = 627,
  [SMALL_STATE(29)] = 656,
  [SMALL_STATE(30)] = 685,
  [SMALL_STATE(31)] = 714,
  [SMALL_STATE(32)] = 743,
  [SMALL_STATE(33)] = 772,
  [SMALL_STATE(34)] = 801,
  [SMALL_STATE(35)] = 822,
  [SMALL_STATE(36)] = 843,
  [SMALL_STATE(37)] = 872,
  [SMALL_STATE(38)] = 901,
  [SMALL_STATE(39)] = 930,
  [SMALL_STATE(40)] = 953,
  [SMALL_STATE(41)] = 984,
  [SMALL_STATE(42)] = 996,
  [SMALL_STATE(43)] = 1022,
  [SMALL_STATE(44)] = 1034,
  [SMALL_STATE(45)] = 1056,
  [SMALL_STATE(46)] = 1068,
  [SMALL_STATE(47)] = 1080,
  [SMALL_STATE(48)] = 1102,
  [SMALL_STATE(49)] = 1128,
  [SMALL_STATE(50)] = 1150,
  [SMALL_STATE(51)] = 1162,
  [SMALL_STATE(52)] = 1188,
  [SMALL_STATE(53)] = 1207,
  [SMALL_STATE(54)] = 1228,
  [SMALL_STATE(55)] = 1247,
  [SMALL_STATE(56)] = 1261,
  [SMALL_STATE(57)] = 1271,
  [SMALL_STATE(58)] = 1293,
  [SMALL_STATE(59)] = 1306,
  [SMALL_STATE(60)] = 1325,
  [SMALL_STATE(61)] = 1339,
  [SMALL_STATE(62)] = 1351,
  [SMALL_STATE(63)] = 1365,
  [SMALL_STATE(64)] = 1377,
  [SMALL_STATE(65)] = 1389,
  [SMALL_STATE(66)] = 1401,
  [SMALL_STATE(67)] = 1414,
  [SMALL_STATE(68)] = 1427,
  [SMALL_STATE(69)] = 1438,
  [SMALL_STATE(70)] = 1449,
  [SMALL_STATE(71)] = 1460,
  [SMALL_STATE(72)] = 1471,
  [SMALL_STATE(73)] = 1482,
  [SMALL_STATE(74)] = 1489,
  [SMALL_STATE(75)] = 1500,
  [SMALL_STATE(76)] = 1511,
  [SMALL_STATE(77)] = 1522,
  [SMALL_STATE(78)] = 1535,
  [SMALL_STATE(79)] = 1542,
  [SMALL_STATE(80)] = 1553,
  [SMALL_STATE(81)] = 1564,
  [SMALL_STATE(82)] = 1575,
  [SMALL_STATE(83)] = 1585,
  [SMALL_STATE(84)] = 1591,
  [SMALL_STATE(85)] = 1597,
  [SMALL_STATE(86)] = 1607,
  [SMALL_STATE(87)] = 1613,
  [SMALL_STATE(88)] = 1619,
  [SMALL_STATE(89)] = 1629,
  [SMALL_STATE(90)] = 1639,
  [SMALL_STATE(91)] = 1649,
  [SMALL_STATE(92)] = 1659,
  [SMALL_STATE(93)] = 1669,
  [SMALL_STATE(94)] = 1679,
  [SMALL_STATE(95)] = 1686,
  [SMALL_STATE(96)] = 1693,
  [SMALL_STATE(97)] = 1698,
  [SMALL_STATE(98)] = 1705,
  [SMALL_STATE(99)] = 1710,
  [SMALL_STATE(100)] = 1715,
  [SMALL_STATE(101)] = 1722,
  [SMALL_STATE(102)] = 1729,
  [SMALL_STATE(103)] = 1734,
  [SMALL_STATE(104)] = 1739,
  [SMALL_STATE(105)] = 1746,
  [SMALL_STATE(106)] = 1753,
  [SMALL_STATE(107)] = 1760,
  [SMALL_STATE(108)] = 1765,
  [SMALL_STATE(109)] = 1769,
  [SMALL_STATE(110)] = 1773,
  [SMALL_STATE(111)] = 1777,
  [SMALL_STATE(112)] = 1781,
  [SMALL_STATE(113)] = 1785,
  [SMALL_STATE(114)] = 1789,
  [SMALL_STATE(115)] = 1793,
  [SMALL_STATE(116)] = 1797,
  [SMALL_STATE(117)] = 1801,
  [SMALL_STATE(118)] = 1805,
  [SMALL_STATE(119)] = 1809,
  [SMALL_STATE(120)] = 1813,
  [SMALL_STATE(121)] = 1817,
  [SMALL_STATE(122)] = 1821,
  [SMALL_STATE(123)] = 1825,
  [SMALL_STATE(124)] = 1829,
  [SMALL_STATE(125)] = 1833,
  [SMALL_STATE(126)] = 1837,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_expression_repeat1, 2),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_repeat1, 2), SHIFT_REPEAT(79),
  [20] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 2),
  [22] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [24] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 1),
  [26] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_name, 1),
  [28] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_key_name, 1),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_lookup, 2),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 3),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_invocation, 4),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_invocation, 5),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 3),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 4),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 4),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern_element, 1),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern_element, 2),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pattern_element_repeat1, 2),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_element_repeat1, 2), SHIFT_REPEAT(67),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_pattern, 5),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_pattern, 4),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_where, 2),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__pattern_element_chain, 2),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_pattern, 3),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__projection_item, 1),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_pattern, 2),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__query, 2),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_map_literal_repeat1, 4),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__query, 1),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__query_repeat2, 2),
  [119] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__query_repeat2, 2), SHIFT_REPEAT(68),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern_element, 3),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [126] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__query_repeat1, 2), SHIFT_REPEAT(70),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__query_repeat1, 2),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_match, 2),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_node_labels_repeat1, 2),
  [149] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_node_labels_repeat1, 2), SHIFT_REPEAT(75),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_labels, 1),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_labels, 2),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [158] = {.entry = {.count = 1, .reusable = false}}, SHIFT(126),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__projection_items, 1),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__projection_items_repeat1, 2),
  [168] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__projection_items_repeat1, 2), SHIFT_REPEAT(22),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [173] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2), SHIFT_REPEAT(26),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_create, 2),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__projection_items, 2),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_label, 2),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label_name, 1),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_relationship_types, 3),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_match, 3),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [196] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_map_literal_repeat1, 2), SHIFT_REPEAT(80),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_map_literal_repeat1, 2),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_relationship_types, 2),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_relationship_types_repeat1, 2),
  [205] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_relationship_types_repeat1, 2), SHIFT_REPEAT(62),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_relationship_types_repeat1, 3),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [220] = {.entry = {.count = 1, .reusable = false}}, SHIFT(122),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cypher, 1),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_relationship_detail, 4),
  [228] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_relationship_detail, 4),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__query, 3),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rel_type_name, 1),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_relationship_detail, 3),
  [236] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_relationship_detail, 3),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_relationship_detail, 2),
  [240] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_relationship_detail, 2),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return, 2),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_properties, 1),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map_literal, 5),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cypher, 2),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map_literal, 6),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map_literal, 2),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__relationship_pattern, 3),
  [270] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [274] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__relationship_pattern, 2),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_cypher(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
