#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 135
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 81
#define ALIAS_COUNT 0
#define TOKEN_COUNT 36
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_SEMI = 1,
  anon_sym_OPTIONAL = 2,
  anon_sym_MATCH = 3,
  anon_sym_LPAREN = 4,
  anon_sym_RPAREN = 5,
  anon_sym_LT_DASH = 6,
  anon_sym_DASH_GT = 7,
  anon_sym_DASH = 8,
  anon_sym_LBRACK = 9,
  anon_sym_RBRACK = 10,
  anon_sym_COLON = 11,
  anon_sym_PIPE = 12,
  anon_sym_LBRACE = 13,
  anon_sym_COMMA = 14,
  anon_sym_RBRACE = 15,
  anon_sym_WHERE = 16,
  anon_sym_CREATE = 17,
  anon_sym_RETURN = 18,
  anon_sym_IN = 19,
  anon_sym_AND = 20,
  aux_sym_expression_token1 = 21,
  aux_sym_expression_token2 = 22,
  anon_sym_NOT = 23,
  anon_sym_XOR = 24,
  anon_sym_OR = 25,
  anon_sym_EQ_TILDE = 26,
  anon_sym_EQ = 27,
  anon_sym_DOT = 28,
  anon_sym_DOLLAR = 29,
  sym_decimal_integer_literal = 30,
  anon_sym_SQUOTE = 31,
  aux_sym_string_literal_token1 = 32,
  anon_sym_DQUOTE = 33,
  aux_sym_string_literal_token2 = 34,
  sym_identifier = 35,
  sym_cypher = 36,
  sym__query = 37,
  sym__reading_clause = 38,
  sym_match = 39,
  sym__pattern = 40,
  sym_pattern_element = 41,
  sym__pattern_element_chain = 42,
  sym__relationship_pattern = 43,
  sym_relationship_detail = 44,
  sym_relationship_types = 45,
  sym_rel_type_name = 46,
  sym_node_pattern = 47,
  sym_node_labels = 48,
  sym_node_label = 49,
  sym_label_name = 50,
  sym_properties = 51,
  sym_map_literal = 52,
  sym_where = 53,
  sym__updating_clause = 54,
  sym_create = 55,
  sym_return = 56,
  sym__projection_items = 57,
  sym__projection_item = 58,
  sym_expression = 59,
  sym_list = 60,
  sym_property_lookup = 61,
  sym_property_key_name = 62,
  sym__schema_name = 63,
  sym__atom = 64,
  sym_parameter = 65,
  sym_function_invocation = 66,
  sym_function_name = 67,
  sym__literal = 68,
  sym_string_literal = 69,
  sym_variable = 70,
  sym__symbolic_name = 71,
  aux_sym__query_repeat1 = 72,
  aux_sym__query_repeat2 = 73,
  aux_sym_pattern_element_repeat1 = 74,
  aux_sym_relationship_types_repeat1 = 75,
  aux_sym_node_labels_repeat1 = 76,
  aux_sym_map_literal_repeat1 = 77,
  aux_sym__projection_items_repeat1 = 78,
  aux_sym_expression_repeat1 = 79,
  aux_sym_list_repeat1 = 80,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SEMI] = ";",
  [anon_sym_OPTIONAL] = "OPTIONAL",
  [anon_sym_MATCH] = "MATCH",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LT_DASH] = "<-",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_DASH] = "-",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_COLON] = ":",
  [anon_sym_PIPE] = "|",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACE] = "}",
  [anon_sym_WHERE] = "WHERE",
  [anon_sym_CREATE] = "CREATE",
  [anon_sym_RETURN] = "RETURN",
  [anon_sym_IN] = "IN",
  [anon_sym_AND] = "AND",
  [aux_sym_expression_token1] = "expression_token1",
  [aux_sym_expression_token2] = "expression_token2",
  [anon_sym_NOT] = "NOT",
  [anon_sym_XOR] = "XOR",
  [anon_sym_OR] = "OR",
  [anon_sym_EQ_TILDE] = "=~",
  [anon_sym_EQ] = "=",
  [anon_sym_DOT] = ".",
  [anon_sym_DOLLAR] = "$",
  [sym_decimal_integer_literal] = "decimal_integer_literal",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_string_literal_token1] = "string_literal_token1",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_literal_token2] = "string_literal_token2",
  [sym_identifier] = "identifier",
  [sym_cypher] = "cypher",
  [sym__query] = "_query",
  [sym__reading_clause] = "_reading_clause",
  [sym_match] = "match",
  [sym__pattern] = "_pattern",
  [sym_pattern_element] = "pattern_element",
  [sym__pattern_element_chain] = "_pattern_element_chain",
  [sym__relationship_pattern] = "_relationship_pattern",
  [sym_relationship_detail] = "relationship_detail",
  [sym_relationship_types] = "relationship_types",
  [sym_rel_type_name] = "rel_type_name",
  [sym_node_pattern] = "node_pattern",
  [sym_node_labels] = "node_labels",
  [sym_node_label] = "node_label",
  [sym_label_name] = "label_name",
  [sym_properties] = "properties",
  [sym_map_literal] = "map_literal",
  [sym_where] = "where",
  [sym__updating_clause] = "_updating_clause",
  [sym_create] = "create",
  [sym_return] = "return",
  [sym__projection_items] = "_projection_items",
  [sym__projection_item] = "_projection_item",
  [sym_expression] = "expression",
  [sym_list] = "list",
  [sym_property_lookup] = "property_lookup",
  [sym_property_key_name] = "property_key_name",
  [sym__schema_name] = "_schema_name",
  [sym__atom] = "_atom",
  [sym_parameter] = "parameter",
  [sym_function_invocation] = "function_invocation",
  [sym_function_name] = "function_name",
  [sym__literal] = "_literal",
  [sym_string_literal] = "string_literal",
  [sym_variable] = "variable",
  [sym__symbolic_name] = "_symbolic_name",
  [aux_sym__query_repeat1] = "_query_repeat1",
  [aux_sym__query_repeat2] = "_query_repeat2",
  [aux_sym_pattern_element_repeat1] = "pattern_element_repeat1",
  [aux_sym_relationship_types_repeat1] = "relationship_types_repeat1",
  [aux_sym_node_labels_repeat1] = "node_labels_repeat1",
  [aux_sym_map_literal_repeat1] = "map_literal_repeat1",
  [aux_sym__projection_items_repeat1] = "_projection_items_repeat1",
  [aux_sym_expression_repeat1] = "expression_repeat1",
  [aux_sym_list_repeat1] = "list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_OPTIONAL] = anon_sym_OPTIONAL,
  [anon_sym_MATCH] = anon_sym_MATCH,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LT_DASH] = anon_sym_LT_DASH,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_WHERE] = anon_sym_WHERE,
  [anon_sym_CREATE] = anon_sym_CREATE,
  [anon_sym_RETURN] = anon_sym_RETURN,
  [anon_sym_IN] = anon_sym_IN,
  [anon_sym_AND] = anon_sym_AND,
  [aux_sym_expression_token1] = aux_sym_expression_token1,
  [aux_sym_expression_token2] = aux_sym_expression_token2,
  [anon_sym_NOT] = anon_sym_NOT,
  [anon_sym_XOR] = anon_sym_XOR,
  [anon_sym_OR] = anon_sym_OR,
  [anon_sym_EQ_TILDE] = anon_sym_EQ_TILDE,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [sym_decimal_integer_literal] = sym_decimal_integer_literal,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_string_literal_token1] = aux_sym_string_literal_token1,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_literal_token2] = aux_sym_string_literal_token2,
  [sym_identifier] = sym_identifier,
  [sym_cypher] = sym_cypher,
  [sym__query] = sym__query,
  [sym__reading_clause] = sym__reading_clause,
  [sym_match] = sym_match,
  [sym__pattern] = sym__pattern,
  [sym_pattern_element] = sym_pattern_element,
  [sym__pattern_element_chain] = sym__pattern_element_chain,
  [sym__relationship_pattern] = sym__relationship_pattern,
  [sym_relationship_detail] = sym_relationship_detail,
  [sym_relationship_types] = sym_relationship_types,
  [sym_rel_type_name] = sym_rel_type_name,
  [sym_node_pattern] = sym_node_pattern,
  [sym_node_labels] = sym_node_labels,
  [sym_node_label] = sym_node_label,
  [sym_label_name] = sym_label_name,
  [sym_properties] = sym_properties,
  [sym_map_literal] = sym_map_literal,
  [sym_where] = sym_where,
  [sym__updating_clause] = sym__updating_clause,
  [sym_create] = sym_create,
  [sym_return] = sym_return,
  [sym__projection_items] = sym__projection_items,
  [sym__projection_item] = sym__projection_item,
  [sym_expression] = sym_expression,
  [sym_list] = sym_list,
  [sym_property_lookup] = sym_property_lookup,
  [sym_property_key_name] = sym_property_key_name,
  [sym__schema_name] = sym__schema_name,
  [sym__atom] = sym__atom,
  [sym_parameter] = sym_parameter,
  [sym_function_invocation] = sym_function_invocation,
  [sym_function_name] = sym_function_name,
  [sym__literal] = sym__literal,
  [sym_string_literal] = sym_string_literal,
  [sym_variable] = sym_variable,
  [sym__symbolic_name] = sym__symbolic_name,
  [aux_sym__query_repeat1] = aux_sym__query_repeat1,
  [aux_sym__query_repeat2] = aux_sym__query_repeat2,
  [aux_sym_pattern_element_repeat1] = aux_sym_pattern_element_repeat1,
  [aux_sym_relationship_types_repeat1] = aux_sym_relationship_types_repeat1,
  [aux_sym_node_labels_repeat1] = aux_sym_node_labels_repeat1,
  [aux_sym_map_literal_repeat1] = aux_sym_map_literal_repeat1,
  [aux_sym__projection_items_repeat1] = aux_sym__projection_items_repeat1,
  [aux_sym_expression_repeat1] = aux_sym_expression_repeat1,
  [aux_sym_list_repeat1] = aux_sym_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_OPTIONAL] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_MATCH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_WHERE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CREATE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RETURN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_IN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_expression_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_expression_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_NOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_XOR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_OR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [sym_decimal_integer_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_literal_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_cypher] = {
    .visible = true,
    .named = true,
  },
  [sym__query] = {
    .visible = false,
    .named = true,
  },
  [sym__reading_clause] = {
    .visible = false,
    .named = true,
  },
  [sym_match] = {
    .visible = true,
    .named = true,
  },
  [sym__pattern] = {
    .visible = false,
    .named = true,
  },
  [sym_pattern_element] = {
    .visible = true,
    .named = true,
  },
  [sym__pattern_element_chain] = {
    .visible = false,
    .named = true,
  },
  [sym__relationship_pattern] = {
    .visible = false,
    .named = true,
  },
  [sym_relationship_detail] = {
    .visible = true,
    .named = true,
  },
  [sym_relationship_types] = {
    .visible = true,
    .named = true,
  },
  [sym_rel_type_name] = {
    .visible = true,
    .named = true,
  },
  [sym_node_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_node_labels] = {
    .visible = true,
    .named = true,
  },
  [sym_node_label] = {
    .visible = true,
    .named = true,
  },
  [sym_label_name] = {
    .visible = true,
    .named = true,
  },
  [sym_properties] = {
    .visible = true,
    .named = true,
  },
  [sym_map_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_where] = {
    .visible = true,
    .named = true,
  },
  [sym__updating_clause] = {
    .visible = false,
    .named = true,
  },
  [sym_create] = {
    .visible = true,
    .named = true,
  },
  [sym_return] = {
    .visible = true,
    .named = true,
  },
  [sym__projection_items] = {
    .visible = false,
    .named = true,
  },
  [sym__projection_item] = {
    .visible = false,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_property_lookup] = {
    .visible = true,
    .named = true,
  },
  [sym_property_key_name] = {
    .visible = true,
    .named = true,
  },
  [sym__schema_name] = {
    .visible = false,
    .named = true,
  },
  [sym__atom] = {
    .visible = false,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_function_invocation] = {
    .visible = true,
    .named = true,
  },
  [sym_function_name] = {
    .visible = true,
    .named = true,
  },
  [sym__literal] = {
    .visible = false,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym__symbolic_name] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__query_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__query_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pattern_element_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_relationship_types_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_node_labels_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_map_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__projection_items_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 132,
  [133] = 133,
  [134] = 134,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(39);
      if (lookahead == '"') ADVANCE(76);
      if (lookahead == '$') ADVANCE(70);
      if (lookahead == '\'') ADVANCE(73);
      if (lookahead == '(') ADVANCE(43);
      if (lookahead == ')') ADVANCE(44);
      if (lookahead == '+') ADVANCE(61);
      if (lookahead == ',') ADVANCE(54);
      if (lookahead == '-') ADVANCE(48);
      if (lookahead == '.') ADVANCE(69);
      if (lookahead == '0') ADVANCE(71);
      if (lookahead == ':') ADVANCE(51);
      if (lookahead == ';') ADVANCE(40);
      if (lookahead == '<') ADVANCE(3);
      if (lookahead == '=') ADVANCE(68);
      if (lookahead == 'A') ADVANCE(18);
      if (lookahead == 'C') ADVANCE(28);
      if (lookahead == 'I') ADVANCE(19);
      if (lookahead == 'M') ADVANCE(4);
      if (lookahead == 'N') ADVANCE(23);
      if (lookahead == 'O') ADVANCE(26);
      if (lookahead == 'R') ADVANCE(11);
      if (lookahead == 'W') ADVANCE(15);
      if (lookahead == 'X') ADVANCE(22);
      if (lookahead == '[') ADVANCE(49);
      if (lookahead == ']') ADVANCE(50);
      if (lookahead == '{') ADVANCE(53);
      if (lookahead == '|') ADVANCE(52);
      if (lookahead == '}') ADVANCE(55);
      if (lookahead == '%' ||
          ('*' <= lookahead && lookahead <= '/')) ADVANCE(62);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(72);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(76);
      if (lookahead == '$') ADVANCE(70);
      if (lookahead == '\'') ADVANCE(73);
      if (lookahead == '-') ADVANCE(48);
      if (lookahead == '0') ADVANCE(71);
      if (lookahead == 'N') ADVANCE(79);
      if (lookahead == '[') ADVANCE(49);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(72);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 2:
      if (lookahead == '(') ADVANCE(43);
      if (lookahead == ')') ADVANCE(44);
      if (lookahead == ':') ADVANCE(51);
      if (lookahead == ']') ADVANCE(50);
      if (lookahead == '{') ADVANCE(53);
      if (lookahead == '}') ADVANCE(55);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 3:
      if (lookahead == '-') ADVANCE(45);
      END_STATE();
    case 4:
      if (lookahead == 'A') ADVANCE(31);
      END_STATE();
    case 5:
      if (lookahead == 'A') ADVANCE(17);
      END_STATE();
    case 6:
      if (lookahead == 'A') ADVANCE(35);
      END_STATE();
    case 7:
      if (lookahead == 'C') ADVANCE(14);
      END_STATE();
    case 8:
      if (lookahead == 'D') ADVANCE(60);
      END_STATE();
    case 9:
      if (lookahead == 'E') ADVANCE(56);
      END_STATE();
    case 10:
      if (lookahead == 'E') ADVANCE(57);
      END_STATE();
    case 11:
      if (lookahead == 'E') ADVANCE(34);
      END_STATE();
    case 12:
      if (lookahead == 'E') ADVANCE(30);
      END_STATE();
    case 13:
      if (lookahead == 'E') ADVANCE(6);
      END_STATE();
    case 14:
      if (lookahead == 'H') ADVANCE(42);
      END_STATE();
    case 15:
      if (lookahead == 'H') ADVANCE(12);
      END_STATE();
    case 16:
      if (lookahead == 'I') ADVANCE(24);
      END_STATE();
    case 17:
      if (lookahead == 'L') ADVANCE(41);
      END_STATE();
    case 18:
      if (lookahead == 'N') ADVANCE(8);
      END_STATE();
    case 19:
      if (lookahead == 'N') ADVANCE(59);
      END_STATE();
    case 20:
      if (lookahead == 'N') ADVANCE(58);
      END_STATE();
    case 21:
      if (lookahead == 'N') ADVANCE(5);
      END_STATE();
    case 22:
      if (lookahead == 'O') ADVANCE(27);
      END_STATE();
    case 23:
      if (lookahead == 'O') ADVANCE(32);
      END_STATE();
    case 24:
      if (lookahead == 'O') ADVANCE(21);
      END_STATE();
    case 25:
      if (lookahead == 'P') ADVANCE(33);
      END_STATE();
    case 26:
      if (lookahead == 'P') ADVANCE(33);
      if (lookahead == 'R') ADVANCE(66);
      END_STATE();
    case 27:
      if (lookahead == 'R') ADVANCE(65);
      END_STATE();
    case 28:
      if (lookahead == 'R') ADVANCE(13);
      END_STATE();
    case 29:
      if (lookahead == 'R') ADVANCE(20);
      END_STATE();
    case 30:
      if (lookahead == 'R') ADVANCE(9);
      END_STATE();
    case 31:
      if (lookahead == 'T') ADVANCE(7);
      END_STATE();
    case 32:
      if (lookahead == 'T') ADVANCE(63);
      END_STATE();
    case 33:
      if (lookahead == 'T') ADVANCE(16);
      END_STATE();
    case 34:
      if (lookahead == 'T') ADVANCE(36);
      END_STATE();
    case 35:
      if (lookahead == 'T') ADVANCE(10);
      END_STATE();
    case 36:
      if (lookahead == 'U') ADVANCE(29);
      END_STATE();
    case 37:
      if (eof) ADVANCE(39);
      if (lookahead == '(') ADVANCE(43);
      if (lookahead == ')') ADVANCE(44);
      if (lookahead == ',') ADVANCE(54);
      if (lookahead == '.') ADVANCE(69);
      if (lookahead == ':') ADVANCE(51);
      if (lookahead == ';') ADVANCE(40);
      if (lookahead == '=') ADVANCE(68);
      if (lookahead == 'A') ADVANCE(18);
      if (lookahead == 'C') ADVANCE(28);
      if (lookahead == 'I') ADVANCE(19);
      if (lookahead == 'M') ADVANCE(4);
      if (lookahead == 'O') ADVANCE(26);
      if (lookahead == 'R') ADVANCE(11);
      if (lookahead == 'X') ADVANCE(22);
      if (lookahead == ']') ADVANCE(50);
      if (lookahead == '}') ADVANCE(55);
      if (('+' <= lookahead && lookahead <= '-')) ADVANCE(61);
      if (lookahead == '%' ||
          ('*' <= lookahead && lookahead <= '/')) ADVANCE(62);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(37)
      END_STATE();
    case 38:
      if (eof) ADVANCE(39);
      if (lookahead == ')') ADVANCE(44);
      if (lookahead == '-') ADVANCE(47);
      if (lookahead == ';') ADVANCE(40);
      if (lookahead == '<') ADVANCE(3);
      if (lookahead == 'C') ADVANCE(28);
      if (lookahead == 'M') ADVANCE(4);
      if (lookahead == 'O') ADVANCE(25);
      if (lookahead == 'R') ADVANCE(11);
      if (lookahead == 'W') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(38)
      END_STATE();
    case 39:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_OPTIONAL);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_MATCH);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_LT_DASH);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '>') ADVANCE(46);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_WHERE);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_CREATE);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_RETURN);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_IN);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_AND);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_expression_token1);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_expression_token2);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_NOT);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_NOT);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_XOR);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_OR);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_EQ_TILDE);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '~') ADVANCE(67);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_decimal_integer_literal);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_decimal_integer_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(72);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(75);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(75);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(aux_sym_string_literal_token2);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(77);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(78);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(aux_sym_string_literal_token2);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(78);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'O') ADVANCE(80);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'T') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 37},
  [3] = {.lex_state = 37},
  [4] = {.lex_state = 37},
  [5] = {.lex_state = 37},
  [6] = {.lex_state = 37},
  [7] = {.lex_state = 37},
  [8] = {.lex_state = 37},
  [9] = {.lex_state = 37},
  [10] = {.lex_state = 37},
  [11] = {.lex_state = 37},
  [12] = {.lex_state = 37},
  [13] = {.lex_state = 37},
  [14] = {.lex_state = 37},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 37},
  [17] = {.lex_state = 37},
  [18] = {.lex_state = 37},
  [19] = {.lex_state = 37},
  [20] = {.lex_state = 37},
  [21] = {.lex_state = 37},
  [22] = {.lex_state = 37},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 38},
  [37] = {.lex_state = 38},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 38},
  [40] = {.lex_state = 37},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 38},
  [43] = {.lex_state = 38},
  [44] = {.lex_state = 38},
  [45] = {.lex_state = 2},
  [46] = {.lex_state = 37},
  [47] = {.lex_state = 37},
  [48] = {.lex_state = 37},
  [49] = {.lex_state = 38},
  [50] = {.lex_state = 38},
  [51] = {.lex_state = 37},
  [52] = {.lex_state = 37},
  [53] = {.lex_state = 37},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 2},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 2},
  [66] = {.lex_state = 2},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 2},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 2},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 1},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 2},
  [82] = {.lex_state = 2},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 2},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 1},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 1},
  [104] = {.lex_state = 2},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 1},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 1},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 77},
  [129] = {.lex_state = 74},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_OPTIONAL] = ACTIONS(1),
    [anon_sym_MATCH] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LT_DASH] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_WHERE] = ACTIONS(1),
    [anon_sym_CREATE] = ACTIONS(1),
    [anon_sym_RETURN] = ACTIONS(1),
    [anon_sym_IN] = ACTIONS(1),
    [anon_sym_AND] = ACTIONS(1),
    [aux_sym_expression_token1] = ACTIONS(1),
    [aux_sym_expression_token2] = ACTIONS(1),
    [anon_sym_NOT] = ACTIONS(1),
    [anon_sym_XOR] = ACTIONS(1),
    [anon_sym_OR] = ACTIONS(1),
    [anon_sym_EQ_TILDE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [sym_decimal_integer_literal] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
  },
  [1] = {
    [sym_cypher] = STATE(134),
    [sym__query] = STATE(102),
    [sym__reading_clause] = STATE(41),
    [sym_match] = STATE(41),
    [sym__updating_clause] = STATE(56),
    [sym_create] = STATE(56),
    [sym_return] = STATE(102),
    [aux_sym__query_repeat1] = STATE(41),
    [aux_sym__query_repeat2] = STATE(56),
    [anon_sym_OPTIONAL] = ACTIONS(3),
    [anon_sym_MATCH] = ACTIONS(5),
    [anon_sym_CREATE] = ACTIONS(7),
    [anon_sym_RETURN] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(13), 1,
      anon_sym_EQ,
    ACTIONS(15), 1,
      anon_sym_DOT,
    STATE(2), 2,
      sym_property_lookup,
      aux_sym_expression_repeat1,
    ACTIONS(11), 17,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_OPTIONAL,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      anon_sym_IN,
      anon_sym_AND,
      aux_sym_expression_token1,
      aux_sym_expression_token2,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_EQ_TILDE,
  [30] = 5,
    ACTIONS(20), 1,
      anon_sym_IN,
    ACTIONS(22), 1,
      anon_sym_EQ,
    ACTIONS(24), 1,
      anon_sym_DOT,
    STATE(2), 2,
      sym_property_lookup,
      aux_sym_expression_repeat1,
    ACTIONS(18), 16,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_OPTIONAL,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      anon_sym_AND,
      aux_sym_expression_token1,
      aux_sym_expression_token2,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_EQ_TILDE,
  [62] = 5,
    ACTIONS(24), 1,
      anon_sym_DOT,
    ACTIONS(28), 1,
      anon_sym_IN,
    ACTIONS(30), 1,
      anon_sym_EQ,
    STATE(3), 2,
      sym_property_lookup,
      aux_sym_expression_repeat1,
    ACTIONS(26), 16,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_OPTIONAL,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      anon_sym_AND,
      aux_sym_expression_token1,
      aux_sym_expression_token2,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_EQ_TILDE,
  [94] = 3,
    ACTIONS(34), 1,
      anon_sym_LPAREN,
    ACTIONS(36), 1,
      anon_sym_EQ,
    ACTIONS(32), 18,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_OPTIONAL,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      anon_sym_IN,
      anon_sym_AND,
      aux_sym_expression_token1,
      aux_sym_expression_token2,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_EQ_TILDE,
      anon_sym_DOT,
  [121] = 2,
    ACTIONS(40), 1,
      anon_sym_EQ,
    ACTIONS(38), 19,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_OPTIONAL,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      anon_sym_IN,
      anon_sym_AND,
      aux_sym_expression_token1,
      aux_sym_expression_token2,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_EQ_TILDE,
      anon_sym_DOT,
  [146] = 2,
    ACTIONS(44), 1,
      anon_sym_EQ,
    ACTIONS(42), 18,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_OPTIONAL,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      anon_sym_IN,
      anon_sym_AND,
      aux_sym_expression_token1,
      aux_sym_expression_token2,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_EQ_TILDE,
      anon_sym_DOT,
  [170] = 2,
    ACTIONS(48), 1,
      anon_sym_EQ,
    ACTIONS(46), 18,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_OPTIONAL,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      anon_sym_IN,
      anon_sym_AND,
      aux_sym_expression_token1,
      aux_sym_expression_token2,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_EQ_TILDE,
      anon_sym_DOT,
  [194] = 2,
    ACTIONS(52), 1,
      anon_sym_EQ,
    ACTIONS(50), 18,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_OPTIONAL,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      anon_sym_IN,
      anon_sym_AND,
      aux_sym_expression_token1,
      aux_sym_expression_token2,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_EQ_TILDE,
      anon_sym_DOT,
  [218] = 2,
    ACTIONS(56), 1,
      anon_sym_EQ,
    ACTIONS(54), 18,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_OPTIONAL,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      anon_sym_IN,
      anon_sym_AND,
      aux_sym_expression_token1,
      aux_sym_expression_token2,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_EQ_TILDE,
      anon_sym_DOT,
  [242] = 2,
    ACTIONS(60), 1,
      anon_sym_EQ,
    ACTIONS(58), 18,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_OPTIONAL,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      anon_sym_IN,
      anon_sym_AND,
      aux_sym_expression_token1,
      aux_sym_expression_token2,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_EQ_TILDE,
      anon_sym_DOT,
  [266] = 2,
    ACTIONS(64), 1,
      anon_sym_EQ,
    ACTIONS(62), 16,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_OPTIONAL,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      anon_sym_AND,
      aux_sym_expression_token1,
      aux_sym_expression_token2,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_EQ_TILDE,
  [288] = 2,
    ACTIONS(68), 1,
      anon_sym_EQ,
    ACTIONS(66), 16,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_OPTIONAL,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      anon_sym_AND,
      aux_sym_expression_token1,
      aux_sym_expression_token2,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_EQ_TILDE,
  [310] = 2,
    ACTIONS(72), 1,
      anon_sym_EQ,
    ACTIONS(70), 16,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_OPTIONAL,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      anon_sym_AND,
      aux_sym_expression_token1,
      aux_sym_expression_token2,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_EQ_TILDE,
  [332] = 12,
    ACTIONS(74), 1,
      anon_sym_NOT,
    ACTIONS(76), 1,
      anon_sym_DOLLAR,
    ACTIONS(78), 1,
      sym_decimal_integer_literal,
    ACTIONS(80), 1,
      anon_sym_SQUOTE,
    ACTIONS(82), 1,
      anon_sym_DQUOTE,
    ACTIONS(84), 1,
      sym_identifier,
    STATE(5), 1,
      sym__symbolic_name,
    STATE(46), 1,
      sym_expression,
    STATE(86), 1,
      sym__projection_item,
    STATE(106), 1,
      sym__projection_items,
    STATE(123), 1,
      sym_function_name,
    STATE(4), 6,
      sym__atom,
      sym_parameter,
      sym_function_invocation,
      sym__literal,
      sym_string_literal,
      sym_variable,
  [374] = 4,
    ACTIONS(86), 1,
      anon_sym_OR,
    ACTIONS(88), 1,
      anon_sym_EQ_TILDE,
    ACTIONS(90), 1,
      anon_sym_EQ,
    ACTIONS(66), 14,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_OPTIONAL,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      anon_sym_AND,
      aux_sym_expression_token1,
      aux_sym_expression_token2,
      anon_sym_XOR,
  [400] = 6,
    ACTIONS(86), 1,
      anon_sym_OR,
    ACTIONS(88), 1,
      anon_sym_EQ_TILDE,
    ACTIONS(90), 1,
      anon_sym_EQ,
    ACTIONS(92), 1,
      anon_sym_AND,
    ACTIONS(94), 2,
      aux_sym_expression_token2,
      anon_sym_XOR,
    ACTIONS(66), 11,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_OPTIONAL,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      aux_sym_expression_token1,
  [430] = 2,
    ACTIONS(98), 1,
      anon_sym_EQ,
    ACTIONS(96), 16,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_OPTIONAL,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      anon_sym_AND,
      aux_sym_expression_token1,
      aux_sym_expression_token2,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_EQ_TILDE,
  [452] = 2,
    ACTIONS(68), 1,
      anon_sym_EQ,
    ACTIONS(66), 16,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_OPTIONAL,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      anon_sym_AND,
      aux_sym_expression_token1,
      aux_sym_expression_token2,
      anon_sym_XOR,
      anon_sym_OR,
      anon_sym_EQ_TILDE,
  [474] = 6,
    ACTIONS(86), 1,
      anon_sym_OR,
    ACTIONS(88), 1,
      anon_sym_EQ_TILDE,
    ACTIONS(90), 1,
      anon_sym_EQ,
    ACTIONS(92), 1,
      anon_sym_AND,
    ACTIONS(94), 2,
      aux_sym_expression_token2,
      anon_sym_XOR,
    ACTIONS(18), 11,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_OPTIONAL,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      aux_sym_expression_token1,
  [504] = 4,
    ACTIONS(86), 1,
      anon_sym_OR,
    ACTIONS(88), 1,
      anon_sym_EQ_TILDE,
    ACTIONS(90), 1,
      anon_sym_EQ,
    ACTIONS(66), 14,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_OPTIONAL,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      anon_sym_AND,
      aux_sym_expression_token1,
      aux_sym_expression_token2,
      anon_sym_XOR,
  [530] = 3,
    ACTIONS(88), 1,
      anon_sym_EQ_TILDE,
    ACTIONS(90), 1,
      anon_sym_EQ,
    ACTIONS(66), 15,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_OPTIONAL,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_CREATE,
      anon_sym_RETURN,
      anon_sym_AND,
      aux_sym_expression_token1,
      aux_sym_expression_token2,
      anon_sym_XOR,
      anon_sym_OR,
  [554] = 11,
    ACTIONS(74), 1,
      anon_sym_NOT,
    ACTIONS(76), 1,
      anon_sym_DOLLAR,
    ACTIONS(78), 1,
      sym_decimal_integer_literal,
    ACTIONS(80), 1,
      anon_sym_SQUOTE,
    ACTIONS(82), 1,
      anon_sym_DQUOTE,
    ACTIONS(84), 1,
      sym_identifier,
    STATE(5), 1,
      sym__symbolic_name,
    STATE(46), 1,
      sym_expression,
    STATE(93), 1,
      sym__projection_item,
    STATE(123), 1,
      sym_function_name,
    STATE(4), 6,
      sym__atom,
      sym_parameter,
      sym_function_invocation,
      sym__literal,
      sym_string_literal,
      sym_variable,
  [593] = 10,
    ACTIONS(74), 1,
      anon_sym_NOT,
    ACTIONS(76), 1,
      anon_sym_DOLLAR,
    ACTIONS(78), 1,
      sym_decimal_integer_literal,
    ACTIONS(80), 1,
      anon_sym_SQUOTE,
    ACTIONS(82), 1,
      anon_sym_DQUOTE,
    ACTIONS(84), 1,
      sym_identifier,
    STATE(5), 1,
      sym__symbolic_name,
    STATE(17), 1,
      sym_expression,
    STATE(123), 1,
      sym_function_name,
    STATE(4), 6,
      sym__atom,
      sym_parameter,
      sym_function_invocation,
      sym__literal,
      sym_string_literal,
      sym_variable,
  [629] = 10,
    ACTIONS(74), 1,
      anon_sym_NOT,
    ACTIONS(76), 1,
      anon_sym_DOLLAR,
    ACTIONS(78), 1,
      sym_decimal_integer_literal,
    ACTIONS(80), 1,
      anon_sym_SQUOTE,
    ACTIONS(82), 1,
      anon_sym_DQUOTE,
    ACTIONS(84), 1,
      sym_identifier,
    STATE(5), 1,
      sym__symbolic_name,
    STATE(22), 1,
      sym_expression,
    STATE(123), 1,
      sym_function_name,
    STATE(4), 6,
      sym__atom,
      sym_parameter,
      sym_function_invocation,
      sym__literal,
      sym_string_literal,
      sym_variable,
  [665] = 10,
    ACTIONS(74), 1,
      anon_sym_NOT,
    ACTIONS(76), 1,
      anon_sym_DOLLAR,
    ACTIONS(78), 1,
      sym_decimal_integer_literal,
    ACTIONS(80), 1,
      anon_sym_SQUOTE,
    ACTIONS(82), 1,
      anon_sym_DQUOTE,
    ACTIONS(84), 1,
      sym_identifier,
    STATE(5), 1,
      sym__symbolic_name,
    STATE(21), 1,
      sym_expression,
    STATE(123), 1,
      sym_function_name,
    STATE(4), 6,
      sym__atom,
      sym_parameter,
      sym_function_invocation,
      sym__literal,
      sym_string_literal,
      sym_variable,
  [701] = 10,
    ACTIONS(74), 1,
      anon_sym_NOT,
    ACTIONS(76), 1,
      anon_sym_DOLLAR,
    ACTIONS(78), 1,
      sym_decimal_integer_literal,
    ACTIONS(80), 1,
      anon_sym_SQUOTE,
    ACTIONS(82), 1,
      anon_sym_DQUOTE,
    ACTIONS(84), 1,
      sym_identifier,
    STATE(5), 1,
      sym__symbolic_name,
    STATE(47), 1,
      sym_expression,
    STATE(123), 1,
      sym_function_name,
    STATE(4), 6,
      sym__atom,
      sym_parameter,
      sym_function_invocation,
      sym__literal,
      sym_string_literal,
      sym_variable,
  [737] = 10,
    ACTIONS(74), 1,
      anon_sym_NOT,
    ACTIONS(76), 1,
      anon_sym_DOLLAR,
    ACTIONS(78), 1,
      sym_decimal_integer_literal,
    ACTIONS(80), 1,
      anon_sym_SQUOTE,
    ACTIONS(82), 1,
      anon_sym_DQUOTE,
    ACTIONS(84), 1,
      sym_identifier,
    STATE(5), 1,
      sym__symbolic_name,
    STATE(48), 1,
      sym_expression,
    STATE(123), 1,
      sym_function_name,
    STATE(4), 6,
      sym__atom,
      sym_parameter,
      sym_function_invocation,
      sym__literal,
      sym_string_literal,
      sym_variable,
  [773] = 10,
    ACTIONS(74), 1,
      anon_sym_NOT,
    ACTIONS(76), 1,
      anon_sym_DOLLAR,
    ACTIONS(78), 1,
      sym_decimal_integer_literal,
    ACTIONS(80), 1,
      anon_sym_SQUOTE,
    ACTIONS(82), 1,
      anon_sym_DQUOTE,
    ACTIONS(84), 1,
      sym_identifier,
    STATE(5), 1,
      sym__symbolic_name,
    STATE(13), 1,
      sym_expression,
    STATE(123), 1,
      sym_function_name,
    STATE(4), 6,
      sym__atom,
      sym_parameter,
      sym_function_invocation,
      sym__literal,
      sym_string_literal,
      sym_variable,
  [809] = 10,
    ACTIONS(74), 1,
      anon_sym_NOT,
    ACTIONS(76), 1,
      anon_sym_DOLLAR,
    ACTIONS(78), 1,
      sym_decimal_integer_literal,
    ACTIONS(80), 1,
      anon_sym_SQUOTE,
    ACTIONS(82), 1,
      anon_sym_DQUOTE,
    ACTIONS(84), 1,
      sym_identifier,
    STATE(5), 1,
      sym__symbolic_name,
    STATE(51), 1,
      sym_expression,
    STATE(123), 1,
      sym_function_name,
    STATE(4), 6,
      sym__atom,
      sym_parameter,
      sym_function_invocation,
      sym__literal,
      sym_string_literal,
      sym_variable,
  [845] = 10,
    ACTIONS(74), 1,
      anon_sym_NOT,
    ACTIONS(76), 1,
      anon_sym_DOLLAR,
    ACTIONS(78), 1,
      sym_decimal_integer_literal,
    ACTIONS(80), 1,
      anon_sym_SQUOTE,
    ACTIONS(82), 1,
      anon_sym_DQUOTE,
    ACTIONS(84), 1,
      sym_identifier,
    STATE(5), 1,
      sym__symbolic_name,
    STATE(20), 1,
      sym_expression,
    STATE(123), 1,
      sym_function_name,
    STATE(4), 6,
      sym__atom,
      sym_parameter,
      sym_function_invocation,
      sym__literal,
      sym_string_literal,
      sym_variable,
  [881] = 10,
    ACTIONS(74), 1,
      anon_sym_NOT,
    ACTIONS(76), 1,
      anon_sym_DOLLAR,
    ACTIONS(78), 1,
      sym_decimal_integer_literal,
    ACTIONS(80), 1,
      anon_sym_SQUOTE,
    ACTIONS(82), 1,
      anon_sym_DQUOTE,
    ACTIONS(84), 1,
      sym_identifier,
    STATE(5), 1,
      sym__symbolic_name,
    STATE(53), 1,
      sym_expression,
    STATE(123), 1,
      sym_function_name,
    STATE(4), 6,
      sym__atom,
      sym_parameter,
      sym_function_invocation,
      sym__literal,
      sym_string_literal,
      sym_variable,
  [917] = 10,
    ACTIONS(74), 1,
      anon_sym_NOT,
    ACTIONS(76), 1,
      anon_sym_DOLLAR,
    ACTIONS(78), 1,
      sym_decimal_integer_literal,
    ACTIONS(80), 1,
      anon_sym_SQUOTE,
    ACTIONS(82), 1,
      anon_sym_DQUOTE,
    ACTIONS(84), 1,
      sym_identifier,
    STATE(5), 1,
      sym__symbolic_name,
    STATE(16), 1,
      sym_expression,
    STATE(123), 1,
      sym_function_name,
    STATE(4), 6,
      sym__atom,
      sym_parameter,
      sym_function_invocation,
      sym__literal,
      sym_string_literal,
      sym_variable,
  [953] = 10,
    ACTIONS(74), 1,
      anon_sym_NOT,
    ACTIONS(76), 1,
      anon_sym_DOLLAR,
    ACTIONS(78), 1,
      sym_decimal_integer_literal,
    ACTIONS(80), 1,
      anon_sym_SQUOTE,
    ACTIONS(82), 1,
      anon_sym_DQUOTE,
    ACTIONS(84), 1,
      sym_identifier,
    STATE(5), 1,
      sym__symbolic_name,
    STATE(52), 1,
      sym_expression,
    STATE(123), 1,
      sym_function_name,
    STATE(4), 6,
      sym__atom,
      sym_parameter,
      sym_function_invocation,
      sym__literal,
      sym_string_literal,
      sym_variable,
  [989] = 10,
    ACTIONS(74), 1,
      anon_sym_NOT,
    ACTIONS(76), 1,
      anon_sym_DOLLAR,
    ACTIONS(78), 1,
      sym_decimal_integer_literal,
    ACTIONS(80), 1,
      anon_sym_SQUOTE,
    ACTIONS(82), 1,
      anon_sym_DQUOTE,
    ACTIONS(84), 1,
      sym_identifier,
    STATE(5), 1,
      sym__symbolic_name,
    STATE(40), 1,
      sym_expression,
    STATE(123), 1,
      sym_function_name,
    STATE(4), 6,
      sym__atom,
      sym_parameter,
      sym_function_invocation,
      sym__literal,
      sym_string_literal,
      sym_variable,
  [1025] = 4,
    STATE(99), 1,
      sym__relationship_pattern,
    ACTIONS(102), 2,
      anon_sym_LT_DASH,
      anon_sym_DASH,
    STATE(37), 2,
      sym__pattern_element_chain,
      aux_sym_pattern_element_repeat1,
    ACTIONS(100), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_OPTIONAL,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_WHERE,
      anon_sym_CREATE,
      anon_sym_RETURN,
  [1047] = 4,
    STATE(99), 1,
      sym__relationship_pattern,
    ACTIONS(106), 2,
      anon_sym_LT_DASH,
      anon_sym_DASH,
    STATE(37), 2,
      sym__pattern_element_chain,
      aux_sym_pattern_element_repeat1,
    ACTIONS(104), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_OPTIONAL,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_WHERE,
      anon_sym_CREATE,
      anon_sym_RETURN,
  [1069] = 13,
    ACTIONS(109), 1,
      anon_sym_LPAREN,
    ACTIONS(111), 1,
      anon_sym_RPAREN,
    ACTIONS(113), 1,
      anon_sym_COLON,
    ACTIONS(115), 1,
      anon_sym_LBRACE,
    ACTIONS(117), 1,
      sym_identifier,
    STATE(39), 1,
      sym_node_pattern,
    STATE(59), 1,
      sym_variable,
    STATE(67), 1,
      sym_node_label,
    STATE(75), 1,
      sym__symbolic_name,
    STATE(76), 1,
      sym_node_labels,
    STATE(113), 1,
      sym_map_literal,
    STATE(118), 1,
      sym_properties,
    STATE(119), 1,
      sym_pattern_element,
  [1109] = 4,
    STATE(99), 1,
      sym__relationship_pattern,
    ACTIONS(102), 2,
      anon_sym_LT_DASH,
      anon_sym_DASH,
    STATE(36), 2,
      sym__pattern_element_chain,
      aux_sym_pattern_element_repeat1,
    ACTIONS(119), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_OPTIONAL,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_WHERE,
      anon_sym_CREATE,
      anon_sym_RETURN,
  [1131] = 7,
    ACTIONS(86), 1,
      anon_sym_OR,
    ACTIONS(88), 1,
      anon_sym_EQ_TILDE,
    ACTIONS(90), 1,
      anon_sym_EQ,
    ACTIONS(92), 1,
      anon_sym_AND,
    ACTIONS(123), 1,
      aux_sym_expression_token1,
    ACTIONS(94), 2,
      aux_sym_expression_token2,
      anon_sym_XOR,
    ACTIONS(121), 4,
      anon_sym_OPTIONAL,
      anon_sym_MATCH,
      anon_sym_CREATE,
      anon_sym_RETURN,
  [1157] = 7,
    ACTIONS(3), 1,
      anon_sym_OPTIONAL,
    ACTIONS(5), 1,
      anon_sym_MATCH,
    ACTIONS(7), 1,
      anon_sym_CREATE,
    ACTIONS(9), 1,
      anon_sym_RETURN,
    STATE(108), 1,
      sym_return,
    STATE(55), 3,
      sym__updating_clause,
      sym_create,
      aux_sym__query_repeat2,
    STATE(58), 3,
      sym__reading_clause,
      sym_match,
      aux_sym__query_repeat1,
  [1183] = 1,
    ACTIONS(125), 10,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_OPTIONAL,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_LT_DASH,
      anon_sym_DASH,
      anon_sym_WHERE,
      anon_sym_CREATE,
      anon_sym_RETURN,
  [1196] = 1,
    ACTIONS(127), 10,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_OPTIONAL,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_LT_DASH,
      anon_sym_DASH,
      anon_sym_WHERE,
      anon_sym_CREATE,
      anon_sym_RETURN,
  [1209] = 1,
    ACTIONS(129), 10,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_OPTIONAL,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_LT_DASH,
      anon_sym_DASH,
      anon_sym_WHERE,
      anon_sym_CREATE,
      anon_sym_RETURN,
  [1222] = 10,
    ACTIONS(111), 1,
      anon_sym_RPAREN,
    ACTIONS(113), 1,
      anon_sym_COLON,
    ACTIONS(115), 1,
      anon_sym_LBRACE,
    ACTIONS(117), 1,
      sym_identifier,
    STATE(59), 1,
      sym_variable,
    STATE(67), 1,
      sym_node_label,
    STATE(75), 1,
      sym__symbolic_name,
    STATE(76), 1,
      sym_node_labels,
    STATE(113), 1,
      sym_map_literal,
    STATE(118), 1,
      sym_properties,
  [1253] = 7,
    ACTIONS(86), 1,
      anon_sym_OR,
    ACTIONS(88), 1,
      anon_sym_EQ_TILDE,
    ACTIONS(90), 1,
      anon_sym_EQ,
    ACTIONS(92), 1,
      anon_sym_AND,
    ACTIONS(123), 1,
      aux_sym_expression_token1,
    ACTIONS(94), 2,
      aux_sym_expression_token2,
      anon_sym_XOR,
    ACTIONS(131), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
  [1278] = 9,
    ACTIONS(86), 1,
      anon_sym_OR,
    ACTIONS(88), 1,
      anon_sym_EQ_TILDE,
    ACTIONS(90), 1,
      anon_sym_EQ,
    ACTIONS(92), 1,
      anon_sym_AND,
    ACTIONS(123), 1,
      aux_sym_expression_token1,
    ACTIONS(133), 1,
      anon_sym_RPAREN,
    ACTIONS(135), 1,
      anon_sym_COMMA,
    STATE(89), 1,
      aux_sym_list_repeat1,
    ACTIONS(94), 2,
      aux_sym_expression_token2,
      anon_sym_XOR,
  [1307] = 7,
    ACTIONS(86), 1,
      anon_sym_OR,
    ACTIONS(88), 1,
      anon_sym_EQ_TILDE,
    ACTIONS(90), 1,
      anon_sym_EQ,
    ACTIONS(92), 1,
      anon_sym_AND,
    ACTIONS(123), 1,
      aux_sym_expression_token1,
    ACTIONS(94), 2,
      aux_sym_expression_token2,
      anon_sym_XOR,
    ACTIONS(137), 3,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
  [1332] = 1,
    ACTIONS(139), 10,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_OPTIONAL,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_LT_DASH,
      anon_sym_DASH,
      anon_sym_WHERE,
      anon_sym_CREATE,
      anon_sym_RETURN,
  [1345] = 1,
    ACTIONS(141), 10,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_OPTIONAL,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_LT_DASH,
      anon_sym_DASH,
      anon_sym_WHERE,
      anon_sym_CREATE,
      anon_sym_RETURN,
  [1358] = 9,
    ACTIONS(86), 1,
      anon_sym_OR,
    ACTIONS(88), 1,
      anon_sym_EQ_TILDE,
    ACTIONS(90), 1,
      anon_sym_EQ,
    ACTIONS(92), 1,
      anon_sym_AND,
    ACTIONS(123), 1,
      aux_sym_expression_token1,
    ACTIONS(135), 1,
      anon_sym_COMMA,
    ACTIONS(143), 1,
      anon_sym_RBRACK,
    STATE(94), 1,
      aux_sym_list_repeat1,
    ACTIONS(94), 2,
      aux_sym_expression_token2,
      anon_sym_XOR,
  [1387] = 9,
    ACTIONS(86), 1,
      anon_sym_OR,
    ACTIONS(88), 1,
      anon_sym_EQ_TILDE,
    ACTIONS(90), 1,
      anon_sym_EQ,
    ACTIONS(92), 1,
      anon_sym_AND,
    ACTIONS(123), 1,
      aux_sym_expression_token1,
    ACTIONS(145), 1,
      anon_sym_COMMA,
    ACTIONS(147), 1,
      anon_sym_RBRACE,
    STATE(90), 1,
      aux_sym_map_literal_repeat1,
    ACTIONS(94), 2,
      aux_sym_expression_token2,
      anon_sym_XOR,
  [1416] = 7,
    ACTIONS(86), 1,
      anon_sym_OR,
    ACTIONS(88), 1,
      anon_sym_EQ_TILDE,
    ACTIONS(90), 1,
      anon_sym_EQ,
    ACTIONS(92), 1,
      anon_sym_AND,
    ACTIONS(123), 1,
      aux_sym_expression_token1,
    ACTIONS(94), 2,
      aux_sym_expression_token2,
      anon_sym_XOR,
    ACTIONS(149), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1440] = 1,
    ACTIONS(151), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_OPTIONAL,
      anon_sym_MATCH,
      anon_sym_RPAREN,
      anon_sym_WHERE,
      anon_sym_CREATE,
      anon_sym_RETURN,
  [1451] = 5,
    ACTIONS(7), 1,
      anon_sym_CREATE,
    ACTIONS(9), 1,
      anon_sym_RETURN,
    STATE(109), 1,
      sym_return,
    ACTIONS(153), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
    STATE(57), 3,
      sym__updating_clause,
      sym_create,
      aux_sym__query_repeat2,
  [1470] = 5,
    ACTIONS(7), 1,
      anon_sym_CREATE,
    ACTIONS(9), 1,
      anon_sym_RETURN,
    STATE(108), 1,
      sym_return,
    ACTIONS(155), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
    STATE(57), 3,
      sym__updating_clause,
      sym_create,
      aux_sym__query_repeat2,
  [1489] = 3,
    ACTIONS(159), 1,
      anon_sym_CREATE,
    ACTIONS(157), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RETURN,
    STATE(57), 3,
      sym__updating_clause,
      sym_create,
      aux_sym__query_repeat2,
  [1503] = 4,
    ACTIONS(162), 1,
      anon_sym_OPTIONAL,
    ACTIONS(165), 1,
      anon_sym_MATCH,
    ACTIONS(168), 2,
      anon_sym_CREATE,
      anon_sym_RETURN,
    STATE(58), 3,
      sym__reading_clause,
      sym_match,
      aux_sym__query_repeat1,
  [1519] = 7,
    ACTIONS(113), 1,
      anon_sym_COLON,
    ACTIONS(115), 1,
      anon_sym_LBRACE,
    ACTIONS(170), 1,
      anon_sym_RPAREN,
    STATE(67), 1,
      sym_node_label,
    STATE(72), 1,
      sym_node_labels,
    STATE(113), 1,
      sym_map_literal,
    STATE(117), 1,
      sym_properties,
  [1541] = 6,
    ACTIONS(117), 1,
      sym_identifier,
    ACTIONS(172), 1,
      anon_sym_RBRACK,
    ACTIONS(174), 1,
      anon_sym_COLON,
    STATE(75), 1,
      sym__symbolic_name,
    STATE(95), 1,
      sym_variable,
    STATE(121), 1,
      sym_relationship_types,
  [1560] = 3,
    ACTIONS(178), 1,
      anon_sym_WHERE,
    STATE(74), 1,
      sym_where,
    ACTIONS(176), 4,
      anon_sym_OPTIONAL,
      anon_sym_MATCH,
      anon_sym_CREATE,
      anon_sym_RETURN,
  [1573] = 3,
    ACTIONS(178), 1,
      anon_sym_WHERE,
    STATE(80), 1,
      sym_where,
    ACTIONS(180), 4,
      anon_sym_OPTIONAL,
      anon_sym_MATCH,
      anon_sym_CREATE,
      anon_sym_RETURN,
  [1586] = 3,
    ACTIONS(113), 1,
      anon_sym_COLON,
    ACTIONS(182), 2,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
    STATE(64), 2,
      sym_node_label,
      aux_sym_node_labels_repeat1,
  [1598] = 3,
    ACTIONS(186), 1,
      anon_sym_COLON,
    ACTIONS(184), 2,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
    STATE(64), 2,
      sym_node_label,
      aux_sym_node_labels_repeat1,
  [1610] = 4,
    ACTIONS(189), 1,
      anon_sym_COLON,
    ACTIONS(191), 1,
      sym_identifier,
    STATE(105), 1,
      sym_rel_type_name,
    STATE(111), 2,
      sym__schema_name,
      sym__symbolic_name,
  [1624] = 4,
    ACTIONS(193), 1,
      anon_sym_RBRACE,
    ACTIONS(195), 1,
      sym_identifier,
    STATE(125), 1,
      sym_property_key_name,
    STATE(6), 2,
      sym__schema_name,
      sym__symbolic_name,
  [1638] = 3,
    ACTIONS(113), 1,
      anon_sym_COLON,
    ACTIONS(197), 2,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
    STATE(63), 2,
      sym_node_label,
      aux_sym_node_labels_repeat1,
  [1650] = 3,
    ACTIONS(201), 1,
      anon_sym_COMMA,
    STATE(68), 1,
      aux_sym__projection_items_repeat1,
    ACTIONS(199), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [1661] = 3,
    ACTIONS(195), 1,
      sym_identifier,
    STATE(126), 1,
      sym_property_key_name,
    STATE(6), 2,
      sym__schema_name,
      sym__symbolic_name,
  [1672] = 3,
    ACTIONS(109), 1,
      anon_sym_LPAREN,
    STATE(39), 1,
      sym_node_pattern,
    STATE(84), 2,
      sym__pattern,
      sym_pattern_element,
  [1683] = 3,
    ACTIONS(191), 1,
      sym_identifier,
    STATE(97), 1,
      sym_rel_type_name,
    STATE(111), 2,
      sym__schema_name,
      sym__symbolic_name,
  [1694] = 4,
    ACTIONS(115), 1,
      anon_sym_LBRACE,
    ACTIONS(204), 1,
      anon_sym_RPAREN,
    STATE(113), 1,
      sym_map_literal,
    STATE(132), 1,
      sym_properties,
  [1707] = 4,
    ACTIONS(206), 1,
      anon_sym_DASH_GT,
    ACTIONS(208), 1,
      anon_sym_DASH,
    ACTIONS(210), 1,
      anon_sym_LBRACK,
    STATE(103), 1,
      sym_relationship_detail,
  [1720] = 1,
    ACTIONS(180), 4,
      anon_sym_OPTIONAL,
      anon_sym_MATCH,
      anon_sym_CREATE,
      anon_sym_RETURN,
  [1727] = 1,
    ACTIONS(32), 4,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COLON,
      anon_sym_LBRACE,
  [1734] = 4,
    ACTIONS(115), 1,
      anon_sym_LBRACE,
    ACTIONS(170), 1,
      anon_sym_RPAREN,
    STATE(113), 1,
      sym_map_literal,
    STATE(117), 1,
      sym_properties,
  [1747] = 3,
    ACTIONS(212), 1,
      anon_sym_COMMA,
    STATE(77), 1,
      aux_sym_list_repeat1,
    ACTIONS(137), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1758] = 3,
    ACTIONS(109), 1,
      anon_sym_LPAREN,
    STATE(39), 1,
      sym_node_pattern,
    STATE(62), 2,
      sym__pattern,
      sym_pattern_element,
  [1769] = 3,
    ACTIONS(217), 1,
      anon_sym_COMMA,
    STATE(68), 1,
      aux_sym__projection_items_repeat1,
    ACTIONS(215), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [1780] = 1,
    ACTIONS(219), 4,
      anon_sym_OPTIONAL,
      anon_sym_MATCH,
      anon_sym_CREATE,
      anon_sym_RETURN,
  [1787] = 3,
    ACTIONS(221), 1,
      sym_identifier,
    STATE(92), 1,
      sym_label_name,
    STATE(91), 2,
      sym__schema_name,
      sym__symbolic_name,
  [1798] = 3,
    ACTIONS(195), 1,
      sym_identifier,
    STATE(11), 1,
      sym_property_key_name,
    STATE(6), 2,
      sym__schema_name,
      sym__symbolic_name,
  [1809] = 3,
    ACTIONS(109), 1,
      anon_sym_LPAREN,
    STATE(39), 1,
      sym_node_pattern,
    STATE(61), 2,
      sym__pattern,
      sym_pattern_element,
  [1820] = 1,
    ACTIONS(223), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_CREATE,
      anon_sym_RETURN,
  [1827] = 3,
    ACTIONS(191), 1,
      sym_identifier,
    STATE(100), 1,
      sym_rel_type_name,
    STATE(111), 2,
      sym__schema_name,
      sym__symbolic_name,
  [1838] = 3,
    ACTIONS(217), 1,
      anon_sym_COMMA,
    STATE(79), 1,
      aux_sym__projection_items_repeat1,
    ACTIONS(225), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [1849] = 3,
    ACTIONS(227), 1,
      anon_sym_RBRACK,
    ACTIONS(229), 1,
      anon_sym_PIPE,
    STATE(96), 1,
      aux_sym_relationship_types_repeat1,
  [1859] = 3,
    ACTIONS(231), 1,
      anon_sym_COMMA,
    ACTIONS(234), 1,
      anon_sym_RBRACE,
    STATE(88), 1,
      aux_sym_map_literal_repeat1,
  [1869] = 3,
    ACTIONS(135), 1,
      anon_sym_COMMA,
    ACTIONS(236), 1,
      anon_sym_RPAREN,
    STATE(77), 1,
      aux_sym_list_repeat1,
  [1879] = 3,
    ACTIONS(145), 1,
      anon_sym_COMMA,
    ACTIONS(238), 1,
      anon_sym_RBRACE,
    STATE(88), 1,
      aux_sym_map_literal_repeat1,
  [1889] = 1,
    ACTIONS(240), 3,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_LBRACE,
  [1895] = 1,
    ACTIONS(242), 3,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_LBRACE,
  [1901] = 1,
    ACTIONS(199), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
  [1907] = 3,
    ACTIONS(135), 1,
      anon_sym_COMMA,
    ACTIONS(244), 1,
      anon_sym_RBRACK,
    STATE(77), 1,
      aux_sym_list_repeat1,
  [1917] = 3,
    ACTIONS(174), 1,
      anon_sym_COLON,
    ACTIONS(246), 1,
      anon_sym_RBRACK,
    STATE(124), 1,
      sym_relationship_types,
  [1927] = 3,
    ACTIONS(248), 1,
      anon_sym_RBRACK,
    ACTIONS(250), 1,
      anon_sym_PIPE,
    STATE(96), 1,
      aux_sym_relationship_types_repeat1,
  [1937] = 3,
    ACTIONS(229), 1,
      anon_sym_PIPE,
    ACTIONS(253), 1,
      anon_sym_RBRACK,
    STATE(87), 1,
      aux_sym_relationship_types_repeat1,
  [1947] = 2,
    ACTIONS(255), 1,
      anon_sym_DASH_GT,
    ACTIONS(257), 1,
      anon_sym_DASH,
  [1954] = 2,
    ACTIONS(259), 1,
      anon_sym_LPAREN,
    STATE(42), 1,
      sym_node_pattern,
  [1961] = 1,
    ACTIONS(261), 2,
      anon_sym_RBRACK,
      anon_sym_PIPE,
  [1966] = 2,
    ACTIONS(263), 1,
      anon_sym_LBRACK,
    STATE(14), 1,
      sym_list,
  [1973] = 2,
    ACTIONS(265), 1,
      ts_builtin_sym_end,
    ACTIONS(267), 1,
      anon_sym_SEMI,
  [1980] = 2,
    ACTIONS(269), 1,
      anon_sym_DASH_GT,
    ACTIONS(271), 1,
      anon_sym_DASH,
  [1987] = 2,
    ACTIONS(273), 1,
      sym_identifier,
    STATE(10), 1,
      sym__symbolic_name,
  [1994] = 1,
    ACTIONS(248), 2,
      anon_sym_RBRACK,
      anon_sym_PIPE,
  [1999] = 1,
    ACTIONS(275), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [2004] = 2,
    ACTIONS(277), 1,
      anon_sym_DASH_GT,
    ACTIONS(279), 1,
      anon_sym_DASH,
  [2011] = 1,
    ACTIONS(153), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [2016] = 1,
    ACTIONS(281), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [2021] = 2,
    ACTIONS(263), 1,
      anon_sym_LBRACK,
    STATE(19), 1,
      sym_list,
  [2028] = 1,
    ACTIONS(283), 2,
      anon_sym_RBRACK,
      anon_sym_PIPE,
  [2033] = 2,
    ACTIONS(285), 1,
      anon_sym_DASH_GT,
    ACTIONS(287), 1,
      anon_sym_DASH,
  [2040] = 1,
    ACTIONS(289), 1,
      anon_sym_RPAREN,
  [2044] = 1,
    ACTIONS(291), 1,
      anon_sym_RPAREN,
  [2048] = 1,
    ACTIONS(293), 1,
      anon_sym_DQUOTE,
  [2052] = 1,
    ACTIONS(293), 1,
      anon_sym_SQUOTE,
  [2056] = 1,
    ACTIONS(204), 1,
      anon_sym_RPAREN,
  [2060] = 1,
    ACTIONS(170), 1,
      anon_sym_RPAREN,
  [2064] = 1,
    ACTIONS(295), 1,
      anon_sym_RPAREN,
  [2068] = 1,
    ACTIONS(297), 1,
      anon_sym_RPAREN,
  [2072] = 1,
    ACTIONS(246), 1,
      anon_sym_RBRACK,
  [2076] = 1,
    ACTIONS(299), 1,
      ts_builtin_sym_end,
  [2080] = 1,
    ACTIONS(301), 1,
      anon_sym_LPAREN,
  [2084] = 1,
    ACTIONS(303), 1,
      anon_sym_RBRACK,
  [2088] = 1,
    ACTIONS(305), 1,
      anon_sym_COLON,
  [2092] = 1,
    ACTIONS(307), 1,
      anon_sym_COLON,
  [2096] = 1,
    ACTIONS(309), 1,
      anon_sym_RPAREN,
  [2100] = 1,
    ACTIONS(311), 1,
      aux_sym_string_literal_token2,
  [2104] = 1,
    ACTIONS(313), 1,
      aux_sym_string_literal_token1,
  [2108] = 1,
    ACTIONS(315), 1,
      anon_sym_MATCH,
  [2112] = 1,
    ACTIONS(317), 1,
      anon_sym_LPAREN,
  [2116] = 1,
    ACTIONS(319), 1,
      anon_sym_RPAREN,
  [2120] = 1,
    ACTIONS(321), 1,
      anon_sym_LPAREN,
  [2124] = 1,
    ACTIONS(323), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 30,
  [SMALL_STATE(4)] = 62,
  [SMALL_STATE(5)] = 94,
  [SMALL_STATE(6)] = 121,
  [SMALL_STATE(7)] = 146,
  [SMALL_STATE(8)] = 170,
  [SMALL_STATE(9)] = 194,
  [SMALL_STATE(10)] = 218,
  [SMALL_STATE(11)] = 242,
  [SMALL_STATE(12)] = 266,
  [SMALL_STATE(13)] = 288,
  [SMALL_STATE(14)] = 310,
  [SMALL_STATE(15)] = 332,
  [SMALL_STATE(16)] = 374,
  [SMALL_STATE(17)] = 400,
  [SMALL_STATE(18)] = 430,
  [SMALL_STATE(19)] = 452,
  [SMALL_STATE(20)] = 474,
  [SMALL_STATE(21)] = 504,
  [SMALL_STATE(22)] = 530,
  [SMALL_STATE(23)] = 554,
  [SMALL_STATE(24)] = 593,
  [SMALL_STATE(25)] = 629,
  [SMALL_STATE(26)] = 665,
  [SMALL_STATE(27)] = 701,
  [SMALL_STATE(28)] = 737,
  [SMALL_STATE(29)] = 773,
  [SMALL_STATE(30)] = 809,
  [SMALL_STATE(31)] = 845,
  [SMALL_STATE(32)] = 881,
  [SMALL_STATE(33)] = 917,
  [SMALL_STATE(34)] = 953,
  [SMALL_STATE(35)] = 989,
  [SMALL_STATE(36)] = 1025,
  [SMALL_STATE(37)] = 1047,
  [SMALL_STATE(38)] = 1069,
  [SMALL_STATE(39)] = 1109,
  [SMALL_STATE(40)] = 1131,
  [SMALL_STATE(41)] = 1157,
  [SMALL_STATE(42)] = 1183,
  [SMALL_STATE(43)] = 1196,
  [SMALL_STATE(44)] = 1209,
  [SMALL_STATE(45)] = 1222,
  [SMALL_STATE(46)] = 1253,
  [SMALL_STATE(47)] = 1278,
  [SMALL_STATE(48)] = 1307,
  [SMALL_STATE(49)] = 1332,
  [SMALL_STATE(50)] = 1345,
  [SMALL_STATE(51)] = 1358,
  [SMALL_STATE(52)] = 1387,
  [SMALL_STATE(53)] = 1416,
  [SMALL_STATE(54)] = 1440,
  [SMALL_STATE(55)] = 1451,
  [SMALL_STATE(56)] = 1470,
  [SMALL_STATE(57)] = 1489,
  [SMALL_STATE(58)] = 1503,
  [SMALL_STATE(59)] = 1519,
  [SMALL_STATE(60)] = 1541,
  [SMALL_STATE(61)] = 1560,
  [SMALL_STATE(62)] = 1573,
  [SMALL_STATE(63)] = 1586,
  [SMALL_STATE(64)] = 1598,
  [SMALL_STATE(65)] = 1610,
  [SMALL_STATE(66)] = 1624,
  [SMALL_STATE(67)] = 1638,
  [SMALL_STATE(68)] = 1650,
  [SMALL_STATE(69)] = 1661,
  [SMALL_STATE(70)] = 1672,
  [SMALL_STATE(71)] = 1683,
  [SMALL_STATE(72)] = 1694,
  [SMALL_STATE(73)] = 1707,
  [SMALL_STATE(74)] = 1720,
  [SMALL_STATE(75)] = 1727,
  [SMALL_STATE(76)] = 1734,
  [SMALL_STATE(77)] = 1747,
  [SMALL_STATE(78)] = 1758,
  [SMALL_STATE(79)] = 1769,
  [SMALL_STATE(80)] = 1780,
  [SMALL_STATE(81)] = 1787,
  [SMALL_STATE(82)] = 1798,
  [SMALL_STATE(83)] = 1809,
  [SMALL_STATE(84)] = 1820,
  [SMALL_STATE(85)] = 1827,
  [SMALL_STATE(86)] = 1838,
  [SMALL_STATE(87)] = 1849,
  [SMALL_STATE(88)] = 1859,
  [SMALL_STATE(89)] = 1869,
  [SMALL_STATE(90)] = 1879,
  [SMALL_STATE(91)] = 1889,
  [SMALL_STATE(92)] = 1895,
  [SMALL_STATE(93)] = 1901,
  [SMALL_STATE(94)] = 1907,
  [SMALL_STATE(95)] = 1917,
  [SMALL_STATE(96)] = 1927,
  [SMALL_STATE(97)] = 1937,
  [SMALL_STATE(98)] = 1947,
  [SMALL_STATE(99)] = 1954,
  [SMALL_STATE(100)] = 1961,
  [SMALL_STATE(101)] = 1966,
  [SMALL_STATE(102)] = 1973,
  [SMALL_STATE(103)] = 1980,
  [SMALL_STATE(104)] = 1987,
  [SMALL_STATE(105)] = 1994,
  [SMALL_STATE(106)] = 1999,
  [SMALL_STATE(107)] = 2004,
  [SMALL_STATE(108)] = 2011,
  [SMALL_STATE(109)] = 2016,
  [SMALL_STATE(110)] = 2021,
  [SMALL_STATE(111)] = 2028,
  [SMALL_STATE(112)] = 2033,
  [SMALL_STATE(113)] = 2040,
  [SMALL_STATE(114)] = 2044,
  [SMALL_STATE(115)] = 2048,
  [SMALL_STATE(116)] = 2052,
  [SMALL_STATE(117)] = 2056,
  [SMALL_STATE(118)] = 2060,
  [SMALL_STATE(119)] = 2064,
  [SMALL_STATE(120)] = 2068,
  [SMALL_STATE(121)] = 2072,
  [SMALL_STATE(122)] = 2076,
  [SMALL_STATE(123)] = 2080,
  [SMALL_STATE(124)] = 2084,
  [SMALL_STATE(125)] = 2088,
  [SMALL_STATE(126)] = 2092,
  [SMALL_STATE(127)] = 2096,
  [SMALL_STATE(128)] = 2100,
  [SMALL_STATE(129)] = 2104,
  [SMALL_STATE(130)] = 2108,
  [SMALL_STATE(131)] = 2112,
  [SMALL_STATE(132)] = 2116,
  [SMALL_STATE(133)] = 2120,
  [SMALL_STATE(134)] = 2124,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_expression_repeat1, 2),
  [13] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_expression_repeat1, 2),
  [15] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_repeat1, 2), SHIFT_REPEAT(82),
  [18] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 2),
  [20] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [22] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 2),
  [24] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [26] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [30] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 1),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_name, 1),
  [36] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 1),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_key_name, 1),
  [40] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property_key_name, 1),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_invocation, 4),
  [44] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_invocation, 4),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_invocation, 5),
  [48] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_invocation, 5),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 3),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 3),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 2),
  [56] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter, 2),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_lookup, 2),
  [60] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property_lookup, 2),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 3),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 3),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 3),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 4),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 4),
  [74] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [84] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [90] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 4),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 4),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern_element, 2),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pattern_element_repeat1, 2),
  [106] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_element_repeat1, 2), SHIFT_REPEAT(73),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern_element, 1),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_where, 2),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__pattern_element_chain, 2),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_pattern, 2),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_pattern, 3),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__projection_item, 1),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_pattern, 4),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_pattern, 5),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_map_literal_repeat1, 4),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern_element, 3),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__query, 2),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__query, 1),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__query_repeat2, 2),
  [159] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__query_repeat2, 2), SHIFT_REPEAT(70),
  [162] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__query_repeat1, 2), SHIFT_REPEAT(130),
  [165] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__query_repeat1, 2), SHIFT_REPEAT(83),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__query_repeat1, 2),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_match, 2),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_match, 3),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_labels, 2),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_node_labels_repeat1, 2),
  [186] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_node_labels_repeat1, 2), SHIFT_REPEAT(81),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_labels, 1),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__projection_items_repeat1, 2),
  [201] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__projection_items_repeat1, 2), SHIFT_REPEAT(23),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [208] = {.entry = {.count = 1, .reusable = false}}, SHIFT(131),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [212] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2), SHIFT_REPEAT(28),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__projection_items, 2),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_match, 4),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_create, 2),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__projection_items, 1),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_relationship_types, 3),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [231] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_map_literal_repeat1, 2), SHIFT_REPEAT(69),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_map_literal_repeat1, 2),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label_name, 1),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_label, 2),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_relationship_types_repeat1, 2),
  [250] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_relationship_types_repeat1, 2), SHIFT_REPEAT(65),
  [253] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_relationship_types, 2),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_relationship_detail, 2),
  [257] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_relationship_detail, 2),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [261] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_relationship_types_repeat1, 3),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cypher, 1),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [271] = {.entry = {.count = 1, .reusable = false}}, SHIFT(133),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [275] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return, 2),
  [277] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_relationship_detail, 4),
  [279] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_relationship_detail, 4),
  [281] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__query, 3),
  [283] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rel_type_name, 1),
  [285] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_relationship_detail, 3),
  [287] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_relationship_detail, 3),
  [289] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_properties, 1),
  [291] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map_literal, 2),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [297] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map_literal, 5),
  [299] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cypher, 2),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [309] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map_literal, 6),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [317] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__relationship_pattern, 2),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [321] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__relationship_pattern, 3),
  [323] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_cypher(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
